Repository umijs/umi, pull requests merged in 2018-12, with the labels that each got.

#1553 feat(umi ui): support config
  .travis.yml
  package.json
  packages/umi-build-dev/src/plugins/commands/ui/.env
  packages/umi-build-dev/src/plugins/commands/ui/.umirc.js
  packages/umi-build-dev/src/plugins/commands/ui/index.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/client.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/model.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/server.js
  packages/umi-build-dev/src/plugins/commands/ui/src/pages/index/model.js
  packages/umi-build-dev/src/utils/setConfig.js
  scripts/build.js
Labels: enhancement

#1603 fix: don't use Array#includes, since it's need polyfill to run in some browsers
  packages/umi/src/runtimePlugin.js
Labels: bug

#1609 fix: uglifyjs don't work after upgrade to webpack-chain@5
  packages/af-webpack/src/getConfig/prod.js
Labels: bug

#1628 fix(block): path prefix
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
Labels: bug

#1633 添加 #1086 文档
  docs/zh/plugin/umi-plugin-react.md
Labels: documentation

#1650 feat: support proxy multiple, specific paths to the same target
  packages/af-webpack/src/getUserConfig/configs/proxy.js
Labels: enhancement

#1666 fix: allow users to turn off code-splitting of dva model separately
  packages/umi-plugin-react/src/index.js
Labels: bug

#1670 feat(block): replace constants in the content of blocks
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.js
  packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.test.js
  packages/umi-build-dev/src/plugins/commands/block/replaceContent.js
  packages/umi-build-dev/src/plugins/commands/block/replaceContent.test.js
  packages/umi-build-dev/yarn.lock
Labels: enhancement

#1692 feat: improve block commands
  .prettierignore
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/yarn.lock
Labels: enhancement

#1695 feat: upgrade deps for babel and webpack
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
  packages/umi/package.json
  packages/umi/yarn.lock
Labels: enhancement

#1696 fix: duplicate react declaration
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/yarn.lock
Labels: bug

#1701 fix: umi don't work in node@8.0.0
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
Labels: bug

#1706 fix(mock): res.body lost when method is delete
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Labels: bug

#1725 fix: minimizer can not be configured
  packages/af-webpack/src/getUserConfig/configs/minimizer.js
Labels: bug

#1726 fix: svg as component don't work
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: bug

#1729 feat: add notify pkg
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
Labels: enhancement
