Repository umijs/umi, pull requests merged in 2018-10, with the labels that each got.

#1184 feat: use config.targets for autoprefixer
  packages/umi-build-dev/src/defaultConfigs/browsers.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: enhancement

#1187 fix: lock babel-plugin-react-require to 3.0.0
  packages/babel-preset-umi/package.json
Labels: bug

#1194 fix: dependency unmatch
  packages/babel-preset-umi/package.json
  packages/umi-build-dev/package.json
Labels: bug

#1198 feat: use umi-tools and fix dependencies for af-webpack
  package.json
  packages/af-webpack/package.json
  packages/umi-build-dev/package.json
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-react/package.json
  packages/umi-test/src/transformers/jsTransformer.js
  packages/umi-test/src/transformers/tsTransformer.js
  packages/umi/package.json
  scripts/build.js
Labels: enhancement

#1199 fix: lost dep address for af-webpack
  packages/af-webpack/package.json
Labels: bug

#1200 feat: new plugin api 'modifyWebpackConfig'
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/getWebpackConfig.js
Labels: enhancement

#1201 Update develop.md
  docs/zh/plugin/develop.md
Labels: documentation

#1204 feat: support don't include @babel/polyfill
  packages/umi-build-dev/src/plugins/targets.js
Labels: enhancement

#1216 fix: use uglifyjs-webpack-plugin@1.x, since 2.x will cause safari10 problem
  packages/af-webpack/package.json
Labels: bug

#1223 fix: ts test don't work
  packages/umi-test/src/transformers/tsTransformer.js
Labels: bug

#1224 feat: print warning instead of error when use `umi g page` and config.routes exists
  packages/umi-build-dev/src/plugins/commands/generate/page.js
Labels: enhancement

#1236 feat: independent hd plugin.
  packages/umi-plugin-hd/README.md
  packages/umi-plugin-hd/index.js
  packages/umi-plugin-hd/package.json
  packages/umi-plugin-hd/template/index.js
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/index.js
Labels: enhancement

#1244 fix: debug logs clear, default no clear
  packages/af-webpack/src/clearConsole.js
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#1243 support runtime plugin use src/app.js|jsx|ts|tsx
  packages/umi-build-dev/src/FilesGenerator.js
Labels: enhancement

#1242 add intl
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-locale/src/index.js
Labels: enhancement

#1174 fix #1129 / memorize withRoutes in renderRoutes.js
  packages/umi/src/renderRoutes.js
Labels: enhancement

#1250 fix: chunk css don't print when no umi.css found
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#1252 fix: cache problem of babel-plugin-macro
  packages/af-webpack/src/getConfig/index.js
  packages/babel-preset-umi/src/webpack-overrides.js
Labels: bug

#1258 feat: support insert chunk scripts in head
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
Labels: enhancement

#1263 feat: support svg as component
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/src/svgr.js
Labels: enhancement

#1267 feat: add umi/prompt
  docs/api/README.md
  docs/zh/api/README.md
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi/src/prompt.js
Labels: enhancement

#1271 feat: upgrade babel-loader to 8.0.4, since it supported .customize in 8.0.3
  packages/af-webpack/package.json
Labels: enhancement

#1273 feat: improve pnp support for url-loader and jest resolver
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/umi-test/package.json
  packages/umi-test/src/index.js
Labels: enhancement

#1275 feat: upgrade dva-loading to 2.1.0-beta.2
  packages/umi-plugin-dva/package.json
Labels: enhancement

#1277 fix: umi -v don't work
  packages/umi/src/cli.js
Labels: bug

#1280 fix: hd plugin not transform and not export in umi-plugin-react
  packages/umi-plugin-hd/package.json
  packages/umi-plugin-hd/src/index.js
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/src/plugins/hd.js
Labels: bug

#1282 feat: support pass props from layouts to child routes
  packages/umi/src/renderRoutes.js
Labels: enhancement

#1302 fix: only generate files in api.onGenerateFiles
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/plugins/targets.js
Labels: bug

#1303 fix: umi test with svg component
  packages/umi-build-dev/src/plugins/commands/test.js
  packages/umi-test/src/index.js
  packages/umi-test/src/transformers/fileTransformer.js
Labels: bug

#1318 fix: theme config validate if value is an absolute path
  packages/af-webpack/src/getConfig/normalizeTheme.js
  packages/af-webpack/src/getUserConfig/configs/theme.js
Labels: bug

#1313 test: improve test case
  package.json
  packages/umi-utils/src/chunkName.test.js
  packages/umi-utils/src/compatDirname.test.js
  packages/umi-utils/src/endWithSlash.test.js
  packages/umi-utils/src/findCSS.js
  packages/umi-utils/src/findCSS.test.js
  packages/umi-utils/src/findJS.js
  packages/umi-utils/src/findJS.test.js
  packages/umi-utils/src/fixtures/compatDirname/have-pkg/package.json
  packages/umi-utils/src/fixtures/compatDirname/no-pkg/.gitkeep
  packages/umi-utils/src/fixtures/findCSS/a.css
  packages/umi-utils/src/fixtures/findCSS/b.less
  packages/umi-utils/src/fixtures/findCSS/c.sass
  packages/umi-utils/src/fixtures/findCSS/d.scss
  packages/umi-utils/src/fixtures/findJS/a.js
  packages/umi-utils/src/fixtures/findJS/b.jsx
  packages/umi-utils/src/fixtures/findJS/c.ts
  packages/umi-utils/src/fixtures/findJS/d.tsx
  packages/umi-utils/src/isUrl.test.js
  packages/umi-utils/src/optsToArray.js
  packages/umi-utils/src/optsToArray.test.js
  packages/umi/src/renderRoutes.js
  packages/umi/src/renderRoutes.test.js
  yarn.lock
Labels: enhancement

#1324 feat: support modifyRouteProps in runtime
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi/src/renderRoutes.js
  packages/umi/src/renderRoutes.test.js
  packages/umi/src/runtimePlugin.js
Labels: enhancement

#1308 fix: suppress ts-jest warning
  packages/umi-test/src/index.js
Labels: bug

#1325 feat: support dynamicImport.loadingComponent as stateless function str
  packages/umi-plugin-react/src/plugins/dynamicImport.js
  packages/umi-plugin-react/src/utils/isReactComponent.js
  packages/umi-plugin-react/src/utils/isReactComponent.test.js
Labels: enhancement

#1329 fix: avoid unexpect title change when ues title plugin with tween
  packages/umi-plugin-react/src/plugins/title/TitleWrapper.js
Labels: bug

#1333 fix: remove unexpect route props set
  packages/umi/src/renderRoutes.js
Labels: bug

#1336 doc: add description about on-demand compilation of antd-pro
  docs/guide/examples.md
  docs/plugin/umi-plugin-react.md
  docs/zh/guide/examples.md
  docs/zh/plugin/umi-plugin-react.md
Labels: documentation

#1337 fix: 每次修改代码都会显示 devServer 信息
  packages/af-webpack/src/dev.js
Labels: bug

#1342 Correction of a slip of the pen
  docs/guide/getting-started.md
Labels: documentation

#1343 fix typo in docs
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: documentation

#1358 feat: manifest publicPath support empty prefix
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: enhancement

#1359 fix: ci env no clipboardy
  packages/af-webpack/src/dev.js
Labels: bug

#1328 feat: support inspect command to inspect internal webpack config (#1314)
  packages/af-webpack/webpack-chain.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/inspect/index.js
  packages/umi/src/cli.js
  packages/umi/src/scripts/inspect.js
Labels: enhancement

#1351 feat: add intl polyfill when targets has android
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/test/index.test.js
Labels: enhancement
