Repository umijs/umi, pull requests merged in 2018-08, with the labels that each got.

#763 doc: improve plugin doc
  docs/plugin/develop.md
  examples/func-test/.umirc.js
  examples/func-test/package.json
  examples/func-test/src/pages/index.js
Labels: documentation

#764 feat: open urls with config.base if specified
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/prepareUrls.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/base.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi/test/base/pages/list.js
Labels: enhancement

#770 feat: add api._modifyConfig()
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/UserConfig.js
Labels: enhancement

#773 fix: window.g_history is undefined when improrted before it's defined
  packages/umi/src/router.js
Labels: bug

#774 fix: add UMI_DIR for umi build
  packages/umi/src/scripts/build.js
Labels: bug

#784 fix: pass exit code for umi dev
  packages/umi/src/scripts/dev.js
Labels: bug

#785 Migrate umi-plugin-routes to umi@2
  packages/umi-plugin-react/README.md
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/test/normal/.umirc.js
  packages/umi-plugin-react/test/normal/pages/a.js
  packages/umi-plugin-react/test/normal/pages/b/c.js
  packages/umi-plugin-routes/README.md
  packages/umi-plugin-routes/package.json
  packages/umi-plugin-routes/src/exclude.js
  packages/umi-plugin-routes/src/index.js
  packages/umi/src/scripts/dev.js
Labels: enhancement

#786 add MIT LICENSE
  LICENSE
  README.md
  packages/af-webpack/package.json
  packages/babel-preset-umi/package.json
  packages/eslint-config-umi/package.json
  packages/umi-build-dev/package.json
  packages/umi-plugin-dll/package.json
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-polyfill/package.json
  packages/umi-plugin-react/package.json
  packages/umi-plugin-routes/package.json
  packages/umi-test/package.json
  packages/umi-utils/package.json
  packages/umi/package.json
Labels: enhancement

#787 Improve dev 404 page
  packages/umi-build-dev/src/plugins/404/NotFound.js
  packages/umi-build-dev/src/plugins/404/NotFound.less
  packages/umi-build-dev/src/plugins/404/index.js
  packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
Labels: enhancement

#789 fix: html path generated is not corrent in umi build when the first route's path is not /
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#790 fix: stylesheet don't work since a typo problem (ref - >rel)
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/getHTMLContent.js
  packages/umi-build-dev/src/html/getHTMLContent.test.js
Labels: bug

#791 feat: use webpackbar for progress
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#792 fix: use api._modifyConfig to supply outputPath don't work properly
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/getConfig/configPlugins/outputPath.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/output-path.js
Labels: bug

#794 fix: move umi.css to the last
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
Labels: bug

#793 feat(umi-utils): find cwd if cwd !== process.cwd(), it's useful when specified APP_ROOT
  packages/umi-utils/src/compatDirname.js
Labels: enhancement

#781 WIP: feat: umi generator
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/plugins/commands/generate/page.js
  packages/umi-build-dev/src/plugins/commands/test.js
  packages/umi-build-dev/template/generators/page.css
  packages/umi-build-dev/template/generators/page.js
  packages/umi-plugin-dva/src/index.js
  packages/umi-plugin-dva/src/model.js
  packages/umi-plugin-dva/template/generators/model.js
  packages/umi/bin/umi.js
Labels: enhancement

#799 feat: set alias @ for src
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: enhancement

#800 fix: runtime error overlay don't work
  packages/af-webpack/src/getConfig/dev.js
  packages/af-webpack/src/webpackHotDevClient.js
Labels: bug

#801 feat: support config.chainWebpackConfig and remove support for webpack.config.js
  packages/af-webpack/src/build.js
  packages/af-webpack/src/getConfig/applyWebpackConfig.js
  packages/af-webpack/src/getConfig/index.js
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/getConfig/configPlugins/chainWebpackConfig.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/getWebpackConfig.js
  packages/umi-build-dev/src/isEqual.js
  packages/umi-build-dev/src/registerBabel.js
Labels: enhancement

#802 feat: use local bin first if found
  packages/umi/bin/umi.js
  packages/umi/cli.js
  packages/umi/package.json
Labels: enhancement

#804 feat: add mountElementId config
  examples/func-test/.umirc.js
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
  packages/umi-build-dev/src/html/fixtures/document.ejs
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/src/plugins/commands/getFilesGenerator.js
  packages/umi-build-dev/src/plugins/mountElementId.js
  packages/umi-build-dev/template/document.ejs
  packages/umi/test/normal/.umirc.js
Labels: enhancement

#806 fix: webpack deprecate tappable warning
  packages/af-webpack/package.json
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/getConfig/dev.js
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#805 Feat: Add stats param for onFail function in build command
  packages/af-webpack/src/build.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-plugin-dll/src/buildDll.js
Labels: enhancement

#809 feat: upgrade to babel@7-rc
  package.json
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/src/registerBabel.js
  packages/babel-preset-umi/README.md
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/src/index.js
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/constants.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi-build-dev/src/registerBabel.js
  packages/umi-test/package.json
  packages/umi-test/src/transformers/jsTransformer.js
  packages/umi/package.json
  scripts/build.js
Labels: enhancement

#811 fix(af-webpack): extraBabelPlugins and extraPluginPresets don't work in api.modifyAFWebpackOpts()
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#815 feat: use react-loadable for umi/dynamic
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/umi/package.json
  packages/umi/src/dynamic.js
Labels: enhancement

#819 fix: mock bug with babel7
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Labels: bug

#818 fix: react mobile plugin bug when option is undefined
  packages/umi-plugin-react/src/plugins/mobile/fastClick.js
  packages/umi-plugin-react/src/plugins/mobile/hd/index.js
Labels: bug

#822 feat(babel-preset-umi): set loose to false by default
  packages/babel-preset-umi/src/index.js
Labels: enhancement

#823 fix(umi-build-dev): mock don't work (again)
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Labels: bug

#826 feat: upgrade most deps to latest
  package.json
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/test/fixtures/alias-in-less/expected/index.css
  packages/af-webpack/test/fixtures/alias-in-less/expected/index.js
  packages/af-webpack/test/fixtures/alias-in-less/index.less
  packages/af-webpack/test/fixtures/alias-in-less/mixin.less
  packages/af-webpack/test/fixtures/alias/expected/index.js
  packages/af-webpack/test/fixtures/copy/expected/index.js
  packages/af-webpack/test/fixtures/css-modules-exclude/expected/index.js
  packages/af-webpack/test/fixtures/disable-dynamic-import/expected/index.js
  packages/af-webpack/test/fixtures/externals/expected/index.js
  packages/af-webpack/test/fixtures/json/expected/index.js
  packages/af-webpack/test/fixtures/less/expected/index.js
  packages/af-webpack/test/fixtures/manifest/expected/index.js
  packages/af-webpack/test/fixtures/sass/expected/index.js
  packages/af-webpack/test/fixtures/theme-via-file/expected/index.js
  packages/af-webpack/test/fixtures/theme/expected/index.js
  packages/af-webpack/test/fixtures/webpack-config-js/expected/index.js
  packages/af-webpack/test/fixtures/webpack-config-js/index.js
  packages/af-webpack/test/fixtures/webpack-config-js/webpack.config.js
  packages/babel-preset-umi/package.json
  packages/umi-build-dev/package.json
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-react/package.json
  packages/umi-test/package.json
  packages/umi-test/src/transformers/jsTransformer.js
  packages/umi-test/src/transformers/tsTransformer.js
  packages/umi/package.json
Labels: enhancement

#829 feat: rename config.chainWebpackConfig to config.chainWebpack
  packages/umi-build-dev/src/getConfig/configPlugins/chainWebpack.js
  packages/umi-build-dev/src/getWebpackConfig.js
Labels: enhancement

#830 feat(umi-plugin-dva): support hmr with umi-plugin-dva
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-dva/src/index.js
Labels: enhancement

#828 fix: locale plugin getLocale bug when not have localstorage
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/src/locale.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
Labels: bug

#834 fix(umi-build-dev): route with routes but without component
  packages/umi-plugin-dva/src/index.js
Labels: bug

#836 fix(umi-test): webpack alias don't work in umi-test properly
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi-build-dev/src/plugins/commands/test.js
  packages/umi/src/scripts/build.js
  packages/umi/src/scripts/dev.js
Labels: bug

#835 fix: history bug when config changed
  packages/umi-build-dev/src/plugins/history.js
Labels: bug

#837 Improve hd and add config.cssnano
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/src/getUserConfig/configs/cssnano.js
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/plugins/mobile/hd/template/flex.js
  packages/umi-plugin-react/src/plugins/mobile/hd/template/index.js
  packages/umi-plugin-react/src/plugins/mobile/hd/template/vw.js
Labels: enhancement

#839 Fix coverage test did not kill child process (Issue #820)
  scripts/startDevServers.js
  scripts/test.js
Labels: bug

#841 fix: test with alias
  packages/umi-build-dev/src/plugins/commands/test.js
Labels: bug

#845 fix: simple filter not yaml comment
  packages/umi-build-dev/src/routes/getYamlConfig.js
  packages/umi-build-dev/src/routes/getYamlConfig.test.js
Labels: bug

#846 feat: generate html files with webpack plugin in umi build
  packages/af-webpack/src/build.js
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/getHtmlGeneratorPlugin.js
Labels: enhancement

#851 fix: isFirstCompile should be true when first compile for dev
  packages/af-webpack/src/dev.js
Labels: bug

#853 feat: extract css in umi dev, hot reload with css-hot-loader
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/css.js
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
Labels: enhancement

#855 fix: css 404 when hash is true in dev mode
  packages/af-webpack/src/getConfig/css.js
Labels: bug

#854 fix: registerBabel failed in windows
  packages/umi-build-dev/src/registerBabel.js
Labels: bug

#859 fix: dynamic import and simplify the async file name
  packages/umi-build-dev/src/routes/routesToJSON.js
  packages/umi-build-dev/src/routes/routesToJSON.test.js
  packages/umi-plugin-react/src/plugins/dynamicImport.js
Labels: bug

#857 feat: use extend2 for deep merge config
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/UserConfig.test.js
  packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.custom.js
  packages/umi-build-dev/src/fixtures/UserConfig/config-config/config/config.js
Labels: enhancement

#860 feat: enable es5ImcompatibleVersions by default
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#861 fix(umi-plugin-dll): umi and umi plugins in dependencies
  packages/umi-plugin-dll/src/buildDll.js
Labels: bug

#862 fix: dynamicImport level wrong and support dynamicImport.level for umi-plugin-react
  packages/umi-build-dev/src/routes/routesToJSON.js
  packages/umi-plugin-react/src/plugins/dynamicImport.js
Labels: enhancement

#863 Feat: Upgrade atool monitor to report more data
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/atoolMonitor.js
  packages/umi/package.json
  packages/umi/src/cli.js
Labels: enhancement

#865 fix: transform ts files with babel
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#866 fix: compatible with legacy mock exports
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Labels: bug

#703 feat: add css-loader option localIdentName
  packages/af-webpack/src/getConfig/css.js
Labels: enhancement

#868 fix: preact don't work and add preact/devtools in umi dev
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/plugins/library.js
Labels: bug

#869 feat: support serverConfig in af-webpack/lib/dev
  packages/af-webpack/src/dev.js
Labels: enhancement

#871 refact: rename umi-plugin-polyfill to umi-plugin-polyfills
  packages/umi-plugin-polyfills/README.md
  packages/umi-plugin-polyfills/package.json
  packages/umi-plugin-polyfills/src/global.js
  packages/umi-plugin-polyfills/src/index.js
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/src/plugins/antd.js
  packages/umi-plugin-react/src/plugins/dll.js
  packages/umi-plugin-react/src/plugins/dva.js
  packages/umi-plugin-react/src/plugins/fastClick.js
  packages/umi-plugin-react/src/plugins/hd/index.js
  packages/umi-plugin-react/src/plugins/hd/template/index.js
  packages/umi-plugin-react/src/plugins/library.js
  packages/umi-plugin-react/src/plugins/locale.js
  packages/umi-plugin-react/src/plugins/polyfills.js
  packages/umi-plugin-react/src/plugins/pwa/index.js
  packages/umi-plugin-react/src/plugins/pwa/registerServiceWorker.js
  packages/umi-plugin-react/src/plugins/routes.js
Labels: enhancement

#873 fix: yarn global install resolve problem
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#878 fix: onPatchRoute args error and fix Route component lack route prop
  packages/umi-build-dev/src/plugins/commands/getRouteManager.js
  packages/umi/src/renderRoutes.js
Labels: bug

#877 docs: migrate to v2
  docs/.vuepress/config.js
  docs/README.md
  docs/api/README.md
  docs/config/README.md
  docs/guide/README.md
  docs/guide/add-404-page.md
  docs/guide/app-structure.md
  docs/guide/config.md
  docs/guide/deploy.md
  docs/guide/env-variables.md
  docs/guide/getting-started.md
  docs/guide/html-template.md
  docs/guide/load-on-demand.md
  docs/guide/migration.md
  docs/guide/router.md
  docs/plugin/README.md
  docs/plugin/develop.md
  docs/plugin/umi-plugin-react.md
Labels: documentation

#879 feat: builddevoptions cwd support dot env
  packages/umi/package.json
  packages/umi/src/buildDevOpts.js
Labels: enhancement

#884 fix: runtimePublicPath config lost
  packages/umi-build-dev/src/getConfig/configPlugins/runtimePublicPath.js
Labels: bug

#885 feat: disable progress plugin when CI is set
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#887 feat: improve umi -v, show more detailed versions
  docs/plugin/develop.md
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/plugins/commands/version.js
  packages/umi-plugin-dva/src/index.js
  packages/umi/src/cli.js
  packages/umi/src/generate.js
  packages/umi/src/version.js
Labels: enhancement

#849 fix: process receive sigint should exit 0
  packages/umi/src/scripts/realDev.js
Labels: bug

#888 feat: improve umi test, support extra args, and specify specs
  packages/umi-build-dev/src/plugins/commands/test.js
  packages/umi-test/src/index.js
Labels: enhancement

#889 fix(umi-plugin-polyfills): options is undefined
  packages/umi-plugin-polyfills/src/index.js
Labels: bug

#883 feat: add plugin title
  docs/plugin/develop.md
  docs/plugin/umi-plugin-react.md
  examples/func-test/.umirc.js
  examples/func-test/src/pages/test.js
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
  packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/src/plugins/title/TitleWrapper.js
  packages/umi-plugin-react/src/plugins/title/index.js
  packages/umi-plugin-react/src/plugins/title/title.test.js
  packages/umi-plugin-react/test/normal.e2e.js
  packages/umi-plugin-react/test/normal/.umirc.js
  packages/umi-plugin-react/test/normal/pages/a.js
  scripts/build.js
Labels: enhancement

#891 fix: child process exit no need settimeout
  packages/umi/src/scripts/realDev.js
Labels: bug

#903 fix: patch routes failed if the route object don't have a key of path
  docs/guide/getting-started.md
  docs/guide/migration.md
  packages/umi-build-dev/src/routes/patchRoutes.js
  packages/umi-build-dev/src/routes/patchRoutes.test.js
Labels: bug

#908 fix: pwa failed
  package.json
  packages/umi-build-dev/src/PluginAPI.js
  scripts/build.js
Labels: bug

#910 fix: customized document path don't work
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#914 fix: remove unnecessary title wrapper for aviod layout component remount when route change.
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/plugins/title/TitleWrapper.js
  packages/umi-plugin-react/src/plugins/title/index.js
  packages/umi-plugin-react/src/plugins/title/title.test.js
Labels: enhancement

#916 fix: fix umi-plugin-locale default config name
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/test/index.test.js
Labels: bug

#912 feat(af-webpack): .json 的优先级应该比 js, ts 低
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#926 fix: should pass down opts.cwd to normalizeTheme
  packages/af-webpack/src/getConfig/css.js
Labels: bug

#929 doc: remove service from plugin doc
  docs/plugin/develop.md
Labels: documentation

#931 fix: build complete slowly
  packages/umi-build-dev/src/plugins/commands/build/index.js
Labels: bug

#937 feat: enable dynamicImport in umi dev
  packages/umi-plugin-dva/src/utils.js
  packages/umi-plugin-react/src/plugins/dynamicImport.js
Labels: enhancement

#939 fix: extraBabelPlugins and extraBabelPresets duplicated
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: bug

#942 fix: mock invalid when proxy is set and api.onOptionChange is used
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
  packages/umi-build-dev/src/plugins/proxy.js
Labels: bug

#948 fix: unexpected rerender caused by route.Routes
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi/src/renderRoutes.js
Labels: bug

#947 fix: failed to add style and script contents
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#949 feat: enhance config, support es6 syntax for config/ directory and watch it's change
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/registerBabel.js
Labels: enhancement

#950 feat: move global.css to last
  packages/umi-build-dev/src/plugins/global-css.js
Labels: enhancement

#957 fix: route props not correct
  packages/umi/src/renderRoutes.js
Labels: bug

#959 fix: global.css don't work in windows
  packages/umi-build-dev/src/plugins/global-css.js
Labels: bug

#958 fix: deprecate pkg break change
  packages/af-webpack/package.json
  packages/umi-build-dev/package.json
Labels: bug

#960 fix: cssnano don't compress url correctly
  packages/af-webpack/src/getConfig/css.js
Labels: bug

#961 feat: bundle-analyzer supports generating stats file
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#963 feat: support polyfill more browsers include ie9, ie10 and ie11
  packages/umi-plugin-polyfills/package.json
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie11.js
  packages/umi-plugin-polyfills/src/ie9.js
  packages/umi-plugin-polyfills/src/index.js
  scripts/build.js
Labels: enhancement
