Repository umijs/umi, pull requests merged in 2018-09, with the labels that each got.

#966 feat: improve d ts
  packages/umi/dynamic.d.ts
Labels: enhancement

#967 feat: use ts-loader for typescript
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#969 feat: af-webpack 支持指定 config file 路径
  packages/af-webpack/bin/af-webpack.js
Labels: enhancement

#968 docs: update with-dva due to new version of umi system
  docs/guide/with-dva.md
Labels: documentation

#974 doc: add english doc for plugin
  docs/plugin/README.md
  docs/plugin/develop.md
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/README.md
  docs/zh/plugin/develop.md
Labels: documentation

#975 fix: ANALYZE=1 umi build don't work and disable monitor
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
Labels: bug

#981 fix: don't generate index.html/index.html if exportStatic is set
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#984 fix: ie10 don't have Map
  packages/umi-plugin-polyfills/src/ie10.js
Labels: bug

#988 feat: add Object polyfills for ie
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie11.js
  packages/umi-plugin-polyfills/src/ie9.js
Labels: enhancement

#990 feat: add number polyfill for umi-plugin-polyfills
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie11.js
  packages/umi-plugin-polyfills/src/ie9.js
Labels: enhancement

#991 fix: umi dev 404 page don't work in IE
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/404/NotFound.js
Labels: bug

#996 fix: add setprototypeof polyfill for ie9 and ie10
  packages/umi-plugin-polyfills/package.json
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie9.js
Labels: bug

#1004 fix(umi-plugin-dva): support mountElementId
  packages/umi-plugin-dva/src/index.js
  packages/umi-plugin-react/test/with-dva/.umirc.js
  packages/umi-plugin-react/test/with-dva/pages/document.ejs
Labels: bug

#1006 feat: add polyfill before global.js, and add a new Plugin API api.addEntryImportAhead
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-plugin-polyfills/src/index.js
Labels: enhancement

#1008 feat: hide conflicting-order-css warnings
  packages/af-webpack/src/getConfig/FilterCSSConflictingWarning.js
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#1011 fix(umi-plugin-dll): exit dll if stats.hasError() [修复 dll 出错时一闪而过并且没有退出的问题]
  packages/af-webpack/src/build.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-plugin-dll/package.json
  packages/umi-plugin-dll/src/buildDll.js
Labels: bug

#1020 fix: runtimePublicPath don't applied in umi dev
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: bug

#1029 fix: locale moment bug [在 locale 插件中引入 moment 相关文件]
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
Labels: bug

#1043 doc: 中文主页 快速上手 link 指向中文 guide 页面
  docs/zh/README.md
Labels: documentation

#1028 feat: add webpack-dev-server config entry (#1016)
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/getConfig/dev.js
  packages/af-webpack/src/getUserConfig/configs/devServer.js
Labels: enhancement

#1055 English translation of docs/api
  docs/api/README.md
Labels: documentation

#1054 doc: add translation for mock-data
  docs/guide/mock-data.md
Labels: documentation

#1069 fix: lock version of webpack-dev-server
  packages/af-webpack/package.json
Labels: bug

#1073 添加对FORK_TS_CHECKER的说明
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
Labels: documentation

#1084 fix: html generate webpack plugin do not throw error correctly
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/plugins/commands/build/chunksToMap.js
  packages/umi-build-dev/src/plugins/commands/getHtmlGeneratorPlugin.js
Labels: bug

#1087 fix(umi-plugin-polyfills): add array polyfills
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie11.js
  packages/umi-plugin-polyfills/src/ie9.js
Labels: bug

#1090 fix: document tpl validate failed in some situations
  packages/umi-build-dev/src/html/HTMLGenerator.js
Labels: bug

#1091 feat: add config.disableRedirectHoist
  docs/config/README.md
  docs/guide/faq.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/getConfig/configPlugins/disableRedirectHoist.js
  packages/umi-build-dev/src/routes/patchRoutes.js
  packages/umi-build-dev/src/routes/patchRoutes.test.js
Labels: enhancement

#1093 feat: improve mock error print
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
  packages/umi-build-dev/src/plugins/mock/index.js
Labels: enhancement

#1097 feat: support config scripts, headScripts, metas and links
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/src/plugins/chunks.js
  packages/umi-plugin-react/src/plugins/headScripts.js
  packages/umi-plugin-react/src/plugins/links.js
  packages/umi-plugin-react/src/plugins/metas.js
  packages/umi-plugin-react/src/plugins/mobile/fastClick.js
  packages/umi-plugin-react/src/plugins/mobile/hd.js
  packages/umi-plugin-react/src/plugins/scripts.js
  packages/umi-plugin-react/test/chunks/.umirc.js
  packages/umi-plugin-react/test/chunks/a.js
  packages/umi-plugin-react/test/chunks/package.json
  packages/umi-plugin-react/test/chunks/pages/index.css
  packages/umi-plugin-react/test/chunks/pages/index.js
  packages/umi-plugin-react/test/chunks/pages/users.css
  packages/umi-plugin-react/test/chunks/pages/users.js
  packages/umi-plugin-react/test/normal.e2e.js
  packages/umi-plugin-react/test/normal/.umirc.js
  packages/umi-plugin-react/test/normal/public/script2.js
Labels: enhancement

#1101 feat: support runtime plugin and src/app.js
  docs/guide/with-dva.md
  docs/plugin/develop.md
  docs/zh/guide/with-dva.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/html/formatChunksMap.js
  packages/umi-build-dev/src/html/formatChunksMap.test.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-build-dev/template/router.js.tpl
  packages/umi-plugin-dva/src/index.js
  packages/umi-plugin-dva/src/runtime.js
  packages/umi-plugin-dva/template/DvaContainer.js
  packages/umi-plugin-react/test/with-dva/app.js
  packages/umi-plugin-react/test/with-dva/models/users.js
  packages/umi-plugin-react/test/with-dva/package.json
  packages/umi-plugin-react/test/with-dva/pages/index.js
  packages/umi/package.json
  packages/umi/src/runtimePlugin.js
  packages/umi/src/runtimePlugin.test.js
  packages/umi/test/runtime/app.js
  packages/umi/test/runtime/package.json
  packages/umi/test/runtime/pages/index.css
  packages/umi/test/runtime/pages/index.js
  scripts/build.js
Labels: enhancement

#1104 feat: tranform typescript files in node_modules and out of cwd
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#1114 feat: improve polyfills with config.targets
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
  packages/umi-build-dev/src/plugins/targets.js
  packages/umi-build-dev/template/polyfills.js.tpl
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-dva/src/index.js
  scripts/build.js
Labels: enhancement

#1132 feat: improve error print
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/plugins/commands/generate/page.js
  packages/umi-build-dev/src/plugins/commands/getRouteManager.js
  packages/umi-build-dev/src/plugins/commands/test.js
  packages/umi-build-dev/src/utils/getCodeFrame.js
  packages/umi-plugin-polyfills/package.json
  packages/umi-plugin-polyfills/src/index.js
  packages/umi-plugin-react/src/index.js
  packages/umi-plugin-react/src/plugins/pwa/index.js
  packages/umi/package.json
  packages/umi/src/cli.js
Labels: enhancement

#1134 feat: lock webpack's version to 4.19.0
  packages/af-webpack/package.json
  packages/umi-plugin-react/package.json
Labels: enhancement

#1135 feat: enable babel-plugin-macros
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/src/index.js
Labels: enhancement

#1140 fix: umi test exit code
  packages/umi-build-dev/src/plugins/commands/test.js
Labels: bug

#1152 页面无限筛选
  packages/umi-plugin-locale/src/locale.js
Labels: bug, wontfix

#1180 feat: improve tsl error formatter
  packages/af-webpack/src/getConfig/index.js
Labels: enhancement

#1181 feat(umi-test): set alias -w for --watch
  packages/umi-build-dev/src/plugins/commands/test.js
Labels: enhancement
