Repository umijs/umi, pull requests merged in 2018-11, with the labels that each got.

#1383 feat: support config.history = 'memory'
  packages/umi-build-dev/src/plugins/history.js
Labels: enhancement

#1403 feat: deprecate browserslist
  packages/umi-build-dev/src/Service.js
Labels: enhancement

#1409 feat: support config.cssPublicPath
  docs/config/README.md
  docs/zh/config/README.md
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/src/getUserConfig/configs/cssPublicPath.js
  packages/af-webpack/test/fixtures/cssPublicPath/.webpackrc
  packages/af-webpack/test/fixtures/cssPublicPath/expected/index.css
  packages/af-webpack/test/fixtures/cssPublicPath/expected/index.js
  packages/af-webpack/test/fixtures/cssPublicPath/expected/static/umi.ecfc8a65.png
  packages/af-webpack/test/fixtures/cssPublicPath/index.css
  packages/af-webpack/test/fixtures/cssPublicPath/index.js
  packages/af-webpack/test/fixtures/cssPublicPath/umi.png
Labels: enhancement

#1413 fix: cssPublicPath in dev mode
  packages/af-webpack/src/getConfig/css.js
Labels: bug

#1402 feat: umi block
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/fixtures/block/alias/config/config.js
  packages/umi-build-dev/src/fixtures/block/alias/routes.js
  packages/umi-build-dev/src/fixtures/block/antdpro/config/config.js
  packages/umi-build-dev/src/fixtures/block/antdpro/config/plugin.config.js
  packages/umi-build-dev/src/fixtures/block/antdpro/config/router.config.js
  packages/umi-build-dev/src/fixtures/block/simple/.umirc.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/block/block.js
  packages/umi-build-dev/src/plugins/commands/block/block.test.js
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
  packages/umi-build-dev/yarn.lock
Labels: enhancement

#1468 fix: upgrade webpackbar and fix build error print
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/src/plugins/commands/build/index.js
Labels: bug

#1444 feat: support `--path` with umi block
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/fixtures/block/alias/routes.js
  packages/umi-build-dev/src/fixtures/block/simple/.umirc.js
  packages/umi-build-dev/src/plugins/commands/block/block.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.js
  packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.result.js
  packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.resultWithLayout.js
  packages/umi-build-dev/src/utils/fixtures/importedRoutes.js
  packages/umi-build-dev/src/utils/fixtures/importedRoutes.result.js
  packages/umi-build-dev/src/utils/fixtures/importedRoutes.resultWithLayout.js
  packages/umi-build-dev/src/utils/fixtures/notRoutes.js
  packages/umi-build-dev/src/utils/fixtures/relativeRouteNode.json
  packages/umi-build-dev/src/utils/fixtures/routeNode.json
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
Labels: enhancement

#1471 fix: upgrade webpack-dev-server, fix npm audit warning
  packages/af-webpack/package.json
Labels: bug

#1472 docs: enhance readability for newbies
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
Labels: documentation

#1501 fix: remove empty title when context.title is undefined
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
  packages/umi-build-dev/template/document.ejs
Labels: bug

#1519 use @types/react-router-dom type definition
  packages/umi/link.d.ts
  packages/umi/navlink.d.ts
  packages/umi/package.json
  packages/umi/prompt.d.ts
  packages/umi/redirect.d.ts
  packages/umi/withRouter.d.ts
Labels: enhancement

#1455 [WIP] feat: umi ui
  package.json
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/plugins/commands/config.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/plugins/commands/rm.js
  packages/umi-build-dev/src/plugins/commands/ui/.umirc.js
  packages/umi-build-dev/src/plugins/commands/ui/index-debug.html
  packages/umi-build-dev/src/plugins/commands/ui/index.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/client.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/model.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/server.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/routes/client.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/routes/model.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/routes/server.js
  packages/umi-build-dev/src/plugins/commands/ui/src/app.js
  packages/umi-build-dev/src/plugins/commands/ui/src/layouts/index.css
  packages/umi-build-dev/src/plugins/commands/ui/src/layouts/index.js
  packages/umi-build-dev/src/plugins/commands/ui/src/models/service.js
  packages/umi-build-dev/src/plugins/commands/ui/src/pages/index/index.js
  packages/umi-build-dev/src/plugins/commands/ui/src/pages/index/model.js
  packages/umi-build-dev/src/utils/setConfig.js
  packages/umi-build-dev/yarn.lock
  rollup.config.js
  yarn.lock
Labels: enhancement

#1536 ts 调用umi组件或方法的时候更加友好
  packages/umi/index.d.ts
  packages/umi/index.js
Labels: enhancement

#1539 fix: 404 route with redirect
  .travis.yml
  packages/af-webpack/src/getUserConfig/configs/devServer.js
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/src/routes/patchRoutes.js
  packages/umi-build-dev/src/routes/patchRoutes.test.js
  packages/umi-build-dev/yarn.lock
  packages/umi-plugin-locale/yarn.lock
  packages/umi-plugin-react/yarn.lock
  packages/umi-test/yarn.lock
  packages/umi/yarn.lock
Labels: bug

#1549 feat: use PAGES_PATH as the first choice
  packages/umi-build-dev/src/getPaths.js
Labels: enhancement

#1561 doc: init umi block doc
  docs/.vuepress/config.js
  docs/guide/block.md
  docs/zh/guide/block.md
Labels: documentation
