Repository umijs/umi, pull requests merged in 2019-01, with the labels that each got.

#1734 upgrade version of css hot loader
  packages/af-webpack/package.json
Labels: enhancement

#1736 fix: cheerio will escape some charactors unexpectedly
  packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
Labels: bug

#1766 feat: support disable system bell via SYSTEM_BELL=none
  packages/af-webpack/src/dev.js
Labels: enhancement

#1767 fix typo in webpack/define description.
  docs/config/README.md
Labels: documentation

#1769 feat: upgrade react-router and react-router-dom to 4.4-beta, fix problems with react-router-config@4.4-beta
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
Labels: enhancement

#1772 fix: disable umi-plugin-routes if routes if configured
  packages/umi-plugin-routes/src/index.js
Labels: bug

#1773 feat: support tree-shaking
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: enhancement

#1774 fix: some dep(e.g. query-string) compile failed when enabled tree-shaking
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#1785 fix: downgrade react-router related library to 4.3 stable
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
Labels: bug

#1784 feat: export Route from react-router-dom
  packages/umi/Route.d.ts
  packages/umi/index.js
  packages/umi/src/Route.js
Labels: enhancement

#1791 mock 支持form-data 请求
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
Labels: enhancement

#1799 fix(umi): index.js lost in publish
  packages/umi/package.json
Labels: bug

#1801 docs: nested routing
  docs/guide/router.md
  docs/zh/guide/router.md
Labels: documentation

#1806 chore: add testcase for mock #1791
  package.json
  packages/umi/test/fixtures/e2e/normal/mock/users.js
  packages/umi/test/normal.e2e.js
  yarn.lock
Labels: enhancement

#1810 fix: locale api is undefined before react app mounted
  packages/umi-plugin-locale/index.d.ts
  packages/umi-plugin-locale/src/locale.js
  packages/umi-plugin-locale/test/locale.test.js
Labels: bug

#1811 fix: warn typo
  packages/umi-plugin-locale/src/locale.js
Labels: bug

#1812 fix: patchRoutes failed with no path route when exportStatic.htmlSuffix is true
  packages/umi-build-dev/src/routes/patchRoutes.js
  packages/umi-build-dev/src/routes/patchRoutes.test.js
Labels: bug

#1815 fix: custom document don't work if base is configured
  packages/umi-build-dev/src/plugins/commands/dev/createRouteMiddleware.js
Labels: bug

#1816 feat: upgrade css-loader to 2
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: enhancement

#1818 fix: css hmr don't work in firefox
  packages/af-webpack/src/getConfig/css.js
Labels: bug

#1819 feat: support eslint check via process.env.ESLINT
  .prettierignore
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/eslint.js
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/yarn.lock
  packages/eslint-config-umi/package.json
  packages/eslint-config-umi/yarn.lock
Labels: enhancement

#1822 fix: downgrade css-loader to 1
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: bug

#1824 fix(umi-test): uncompatible with esm umi api
  packages/umi-test/src/index.js
Labels: bug

#1826 feat: upgrade deps autorefixer@9.4.5 and postcss@7.0.11
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: enhancement

#1829 doc: improve docs
  docs/config/README.md
  docs/guide/create-umi-app.md
  docs/guide/env-variables.md
  docs/zh/config/README.md
  docs/zh/guide/create-umi-app.md
  docs/zh/guide/env-variables.md
Labels: documentation

#1839 feat: improve umi g
  .prettierignore
  package.json
  packages/umi-build-dev/src/BasicGenerator.js
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/plugins/commands/generate/generators/layout/index.js
  packages/umi-build-dev/src/plugins/commands/generate/generators/layout/templates/layout.css
  packages/umi-build-dev/src/plugins/commands/generate/generators/layout/templates/layout.js
  packages/umi-build-dev/src/plugins/commands/generate/generators/page/index.js
  packages/umi-build-dev/src/plugins/commands/generate/generators/page/templates/page.css
  packages/umi-build-dev/src/plugins/commands/generate/generators/page/templates/page.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  yarn.lock
Labels: enhancement

#1844 feat: warn if BABEL_POLYFILL is set to none
  .travis.yml
  docs/guide/env-variables.md
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/plugins/targets.js
Labels: enhancement

#1848 Update examples
  docs/zh/guide/examples.md
Labels: documentation

#1850 fix: title locale bug when separator not include space
  packages/umi-build-dev/src/routes/routesToJSON.js
  packages/umi-build-dev/src/routes/routesToJSON.test.js
  packages/umi-plugin-react/src/plugins/title/index.js
  packages/umi-plugin-react/src/plugins/title/template/TitleWrapper.js.tpl
  packages/umi-plugin-react/test/normal.e2e.js
  packages/umi-plugin-react/test/normal/.umirc.js
  packages/umi-plugin-react/test/normal/locales/en-US.js
  packages/umi-plugin-react/test/normal/locales/zh-CN.js
  packages/umi-plugin-react/test/normal/pages/a.js
Labels: bug

#1851 fix: use onGenerateFiles for generate title temp file for fix build bug
  packages/umi-plugin-react/src/plugins/title/index.js
Labels: bug

#1853 feat: support config autoprefixer
  docs/config/README.md
  docs/zh/config/README.md
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/src/getUserConfig/configs/autoprefixer.js
  packages/af-webpack/test/fixtures/autoprefixer/.webpackrc
  packages/af-webpack/test/fixtures/autoprefixer/expected/index.css
  packages/af-webpack/test/fixtures/autoprefixer/expected/index.js
  packages/af-webpack/test/fixtures/autoprefixer/index.js
  packages/af-webpack/test/fixtures/autoprefixer/index.less
Labels: enhancement

#1858 fix: manifest srcPath with query build error
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
Labels: bug

#1866 feat: support onRouteChange({ location, routes }) in app.js
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/template/router.js.tpl
  packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/umi.js
  packages/umi/test/fixtures/build/export-static/expected/umi.js
  packages/umi/test/fixtures/build/simple/expected/umi.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/umi.js
  packages/umi/test/fixtures/e2e/normal/app.js
  packages/umi/test/normal.e2e.js
Labels: enhancement

#1877 feat: support env UMI_TEMP_DIR and UMI_CONFIG_FILE
  packages/umi-build-dev/src/constants.js
  packages/umi-build-dev/src/getPaths.js
Labels: enhancement

#1871 fix: route.component could be absolute
  packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
Labels: bug

#1881 fix: not throw error in production env when moduleBeforeRendererPromi…
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/umi.js
  packages/umi/test/fixtures/build/export-static/expected/umi.js
  packages/umi/test/fixtures/build/simple/expected/umi.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/umi.js
Labels: bug

#1884 feat: upgrade cssnano@4.1.8
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: enhancement

#1885 fix: missing prompt.d.ts in package files
  packages/umi/package.json
Labels: bug

#1887 feat(umi-plugin-react/antd): support config libraryDirectory for babel-plugin-import
  packages/umi-plugin-react/src/plugins/antd.js
Labels: enhancement

#1888 fix: upgrade babel to 7.3, fix @babel/runtime version conflict problem
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
  packages/umi/package.json
  packages/umi/yarn.lock
Labels: bug

#1889 feat: upgrade to babel@7.3
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/package.json
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-test/package.json
  packages/umi/package.json
Labels: enhancement

#1890 feat: upgrade babel to 7.3.1
  packages/af-webpack/package.json
  packages/babel-preset-umi/package.json
Labels: enhancement

#1893 feat: lock @babel/runtime's version for files in project
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/src/index.js
  packages/babel-preset-umi/yarn.lock
Labels: enhancement

#1900 feat: The official mirror source is used by everyone
  .yarnrc
Labels: enhancement

#1909 fix: getRouteConfigFromDir Convert Windows backslash paths to slash paths
  packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
  packages/umi-plugin-dva/src/index.test.js
Labels: bug

#1912 doc: incorrect runtimePublicPath link
  docs/guide/deploy.md
  docs/zh/guide/deploy.md
Labels: documentation
