Repository umijs/umi, pull requests merged in 2019-08, with the labels that each got.

#2787 doc: add blockConfig doc
  docs/guide/block.md
  docs/plugin/develop.md
  docs/zh/guide/block.md
  docs/zh/plugin/develop.md
Labels: pr(documentation)

#2876 fix: upperCamelCase block import identifier
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
Labels: pr(bug)

#2922 fix: ssr styles shake
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/yarn.lock
  packages/umi/test/dev.e2e.js
  packages/umi/test/fixtures/dev/ssr-styles/.umirc.js
  packages/umi/test/fixtures/dev/ssr-styles/pages/index.js
  packages/umi/test/fixtures/dev/ssr-styles/pages/index.module.less
  packages/umi/test/fixtures/dev/ssr-styles/pages/news.js
  packages/umi/test/fixtures/dev/ssr-styles/pages/news.less
  scripts/startDevServers.js
Labels: pr(bug)

#2924 fix: onStartAsync error handler
  packages/umi-build-dev/src/plugins/commands/dev/index.js
Labels: pr(bug)

#2906 feat: ssr disableExternal
  circle.yml
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/Service.test.js
  packages/umi-build-dev/src/fixtures/Service/plugin-ssr/disableExternal/.umirc.js
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-types/config.d.ts
Labels: pr(enhancement)

#2898 fix(umi-plugin-react): pwa srcPath local path error
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
Labels: pr(bug)

#2934 fix: ci and pwa win path
  lerna.json
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.test.js
  packages/umi/test/fixtures/dev/ssr-styles/pacakge.json
  scripts/startDevServers.js
Labels: pr(bug)

#2940 chore: update yarn.lock
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/yarn.lock
  packages/umi-build-dev/yarn.lock
  packages/umi-core/yarn.lock
  packages/umi-mock/yarn.lock
  packages/umi-plugin-auto-externals/yarn.lock
  packages/umi-plugin-dll/yarn.lock
  packages/umi-plugin-dva/yarn.lock
  packages/umi-plugin-locale/yarn.lock
  packages/umi-plugin-react/yarn.lock
  packages/umi-serve/yarn.lock
  packages/umi-test/yarn.lock
  packages/umi-types/yarn.lock
  packages/umi-utils/yarn.lock
  packages/umi/yarn.lock
  yarn.lock
Labels: pr(chore)

#2955 fix: history won't changed after the config changed
  packages/umi-build-dev/src/plugins/history.js
Labels: pr(bug)

#2933 fix: ssr location query not pass
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi/test/fixtures/build/ssr/pages/index.js
  packages/umi/test/fixtures/build/ssr/test.js
  scripts/startDevServers.js
Labels: pr(bug)

#2938 feat: ssr getInitialProps add req, res params
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/template/entry.js.tpl
Labels: pr(enhancement)

#2964 fix: external test ci when version upd
  packages/umi/test/fixtures/build/auto-external/test.js
Labels: pr(bug)

#2969 fix: windows平台mock文件，不能热更新的问题
  packages/umi-mock/package.json
  packages/umi-mock/src/createMiddleware.js
Labels: pr(bug)

#2941 fix: LocaleProvider warning after antd@3.21
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
Labels: pr(bug)

#2973 fix: locale detection for lang only locales
  packages/umi-plugin-locale/examples/base/src/locale/sk.js
  packages/umi-plugin-locale/examples/base/src/page/temp/locale/sk.js
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/test/index.test.js
Labels: pr(bug)

#2985 dep: upgrade @types/react
  packages/umi/package.json
Labels: pr(dependency)

#2992 Revert "fix: LocaleProvider warning after antd@3.21 (#2941)"
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
Labels: pr(bug)

#3000 feat: expose internal "styleLoader" option.
  packages/af-webpack/src/getUserConfig/configs/styleLoader.js
Labels: pr(enhancement)

#2993 fix: antd ConfigProvider not found
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
Labels: pkg(umi-plugin-locale), pr(bug)

#2991 feat: add env CLEAR_OUTPUT
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/build.js
Labels: pr(enhancement)

#3002 feat: do not exit process when build is under watch mode
  packages/af-webpack/src/build.js
Labels: pr(enhancement)

#3016 fix: umi ssr dev when add independent entry
  packages/umi-build-dev/src/getWebpackConfig.ts
Labels: pr(enhancement), type(ssr)

#3020 doc: add writeTmpFile api doc
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: pr(documentation)

#3027 feat(umi): add mergeAsyncConfig api to support async runtime config
  packages/umi/src/runtimePlugin.js
  packages/umi/src/runtimePlugin.test.js
  packages/umi/src/utils.js
Labels: pr(enhancement)

#3034 fix: localeWrapper console
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
Labels: pr(bug)

#3032 feat: fast gitHub use gitee
  packages/umi-utils/src/getFastGithub.js
Labels: pr(enhancement)

#3102 fix(umi-ui): umd file of ui tasks is lost
  packages/umi-ui-tasks/src/index.ts
Labels: pr(bug)

#3105 feat(umi-ui): disable local check with UI_CHECK_LOCAL=none
  packages/umi-ui/src/UmiUI.ts
Labels: pr(enhancement)

#3106 fix(umi-ui): dev task exit code
  packages/umi-ui-tasks/src/server/core/Tasks/Base.ts
  packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts
  packages/umi/src/scripts/dev.js
Labels: pr(bug)
