Repository umijs/umi, pull requests merged in 2019-11, with the labels that each got.

#3541 dep(umi-plugin-dva): upgrade to ^2.6.0-beta.16
  packages/af-webpack/yarn.lock
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-dva/yarn.lock
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/src/getClientScript.test.ts
  packages/umi-ui/yarn.lock
Labels: pr(dependency)

#3546 fix: onRouteChange execute multiple times when dva is enabled
  packages/umi-build-dev/template/router.js.tpl
Labels: pr(bug)

#3547 fix: give getBasicUI default Value
  packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
Labels: pkg(umi-ui), pr(bug)

#3553 fix: umi-plugin-locale ssr node env module bug
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-react/locale/index.js
Labels: pr(bug), type(ssr)

#3560 doc: the difference between SPA and SSR site in SEO
  docs/guide/ssr.md
  docs/zh/guide/ssr.md
Labels: pr(documentation)

#3567 docs: hd fastclick docs
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
Labels: pr(documentation)

#3570 chore: plugin error console when load failed
  packages/umi-build-dev/src/Service.js
Labels: pr(chore)

#3571 feat(plugin): add api.onExit
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi/src/scripts/realDev.js
Labels: pr(enhancement)

#3581 fix(umi-ui): UMI_UI_PORT env don't work
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3573 fix: ssr render bug when umi.css not exist
  packages/umi-build-dev/.npmignore
  packages/umi-build-dev/src/plugins/commands/__snapshots__/replaceChunkMaps.test.js.snap
  packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.test.js
  packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.ts
Labels: pr(bug), type(ssr)

#3582 dep: upgrade typescript to 3.7
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-plugin-dva/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: pr(dependency)

#3527 chore: add outputPath blacklist
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/getConfig/configPlugins/outputPath.js
  packages/umi-build-dev/src/getConfig/test/outputPath.test.js
Labels: pr(chore)

#3583 fix(Service): printUmiError defined twice
  packages/umi-build-dev/src/Service.js
Labels: pr(bug)

#3587 fix: highestPort should always higher than basePort
  packages/af-webpack/src/getPort.js
Labels: pr(bug)

#3596 fix(umi-ui): block add don't work and task env problem
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
Labels: pr(bug)

#3600 fix: TS 项目下 addUmiExports 缺乏 API 类型推导的问题
  packages/umi-build-dev/src/plugins/importFromUmi.js
Labels: pr(bug)

#3599 feat(umi-ui): support layout block
  packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/constants.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/GUmiUIFlag.tsx
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/export-function/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/ibp-normal/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/ibp-normal/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/layout/config.json
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/layout/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/layout/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/index.tsx
Labels: pr(enhancement)

#3622 fix(umi-ui): umi ui ternmial log use multi instance
  packages/umi-ui-tasks/src/server/core/TaskManger.ts
  packages/umi-ui-tasks/src/server/core/Tasks/Base.ts
  packages/umi-ui-tasks/src/server/index.ts
  packages/umi-ui-tasks/src/ui/components/Build/index.tsx
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
  packages/umi-ui-tasks/src/ui/components/Install/index.tsx
  packages/umi-ui-tasks/src/ui/components/Lint/index.tsx
  packages/umi-ui-tasks/src/ui/components/Test/index.tsx
  packages/umi-ui-tasks/src/ui/model/index.ts
  packages/umi-ui-tasks/src/ui/util/terminal.ts
Labels: pr(bug)

#3609 fix: window.g_initialData block render thread when ssr
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/plugins/commands/getHtmlGenerator.js
Labels: pr(bug), type(ssr)

#3636 fix: umi bigfish ui version check, jsdelivr use latest
  docs/guide/faq.md
  docs/zh/guide/faq.md
  packages/umi-plugin-ui/src/plugins/dashboard/index.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx
  packages/umi-ui/src/UmiUI.ts
Labels: pr(chore)

#3638 chore: improve umi ui
  packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx
Labels: pkg(umi-plugin-ui), pr(chore)

#3637 fix: ui title undefined, error page, auto exec in task page, analyze
  docs/guide/faq.md
  docs/zh/guide/faq.md
  packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/index.tsx
  packages/umi-plugin-ui/package.json
  packages/umi-plugin-ui/src/bubble/Bubble.jsx
  packages/umi-plugin-ui/src/bubble/Logo.jsx
  packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui/action.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/setting.module.less
  packages/umi-plugin-ui/src/plugins/dashboard/ui/setting.tsx
  packages/umi-types/ui.d.ts
  packages/umi-ui-tasks/src/ui.tsx
  packages/umi-ui-tasks/src/ui/components/Build/index.tsx
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
  packages/umi-ui-tasks/src/ui/components/Lint/index.tsx
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
  packages/umi-ui/client/src/getAnalyze.ts
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/pages/loading/actions/openFile.tsx
  scripts/antd-pro.sh
Labels: pkg(umi-plugin-ui), pr(bug)

#3641 fix(umi-ui): terminal focus when visible
  packages/umi-ui/client/src/components/Shell/index.tsx
Labels: pr(chore)

#3642 feat(block): extract block content when adding layout block
  packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/Foo.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/config.json
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/fixtures/extract-block/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/util.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/AddBlockFormForUI.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/write_routes.ts
Labels: pr(enhancement)

#3646 feat: addPanel add renderTitle attribute for user custom
  packages/umi-build-dev/src/plugins/commands/block/ui/client/index.tsx
  packages/umi-types/ui.d.ts
  packages/umi-ui/client/src/layouts/Dashboard.tsx
Labels: pkg(umi-ui), pr(enhancement)

#3649 fix: umi-ui dashboard welcome card style
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less
Labels: pr(chore)

#3651 fix: rss ui cache
  packages/umi-plugin-ui/src/plugins/dashboard/index.ts
Labels: pr(chore)

#3653 feat: support get port via api.service.port in development mode
  packages/af-webpack/package.json
  packages/af-webpack/src/dev.js
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/dev/getPort.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/yarn.lock
  packages/umi-plugin-ui/yarn.lock
Labels: pr(enhancement)

#3662 fix: shell socket ins reset
  packages/umi-ui/client/src/components/Shell/index.tsx
Labels: pr(bug)

#3670 fix: Dashboard card ellipsis in Firefox
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less
  packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.module.less
  packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx
Labels: pr(bug)

#3678 fix: ssr server render history object oom
  packages/umi-build-dev/template/entry.js.tpl
Labels: pr(bug)

#3682 docs: update readme
  README.md
  README_zh-CN.md
Labels: pr(documentation)

#3673 feat: enable ejs include api
  packages/umi-build-dev/src/html/HTMLGenerator.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
  packages/umi-build-dev/src/html/fixtures/document-partial.ejs
  packages/umi-build-dev/src/html/fixtures/document-with-include.ejs
Labels: pr(enhancement)

#3696 fix: ssr perf
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/template/entry.js.tpl
Labels: pr(bug), type(ssr)

#3697 fix: umi-ui antd version
  packages/umi-ui/client/.umirc.ts
Labels: pkg(umi-ui), pr(chore)

#3698 fix: use ts file for tmp umi exports
  packages/af-webpack/src/getWebpackConfig/index.js
  packages/af-webpack/src/getWebpackConfig/tsconfig.default.json
  packages/af-webpack/test/fixtures/generate-css-modules-typings/.webpackrc
  packages/af-webpack/test/fixtures/generate-css-modules-typings/expected/index.css
  packages/af-webpack/test/fixtures/generate-css-modules-typings/expected/index.css.d.ts
  packages/af-webpack/test/fixtures/generate-css-modules-typings/index.css
  packages/af-webpack/test/fixtures/generate-css-modules-typings/index.ts
  packages/umi-build-dev/src/plugins/importFromUmi.js
  packages/umi/test/build.e2e.ts
Labels: pr(bug)

#3702 fix: umi-ui data parse error
  packages/umi-ui/src/Config.test.ts
  packages/umi-ui/src/Config.ts
  packages/umi-ui/src/fixtures/Config/illegal.json
Labels: pkg(umi-ui), pr(bug)

#3687 feat: ui footer add open editor
  docs/guide/faq.md
  docs/zh/guide/faq.md
  packages/umi-mock/src/createMiddleware.test.js
  packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui/action.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/plugins/dailyReport.tsx
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
  packages/umi-ui/client/src/components/icons/Editor.tsx
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
Labels: pkg(umi-ui), pr(enhancement)

#3703 fix: ignore *.d.ts in convensional routes
  packages/umi-build-dev/src/routes/fixtures/ignore-files/a.d.ts
  packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
Labels: pr(bug)

#3713 fix: 修复lerna官网链接错误
  README.md
  README_zh-CN.md
Labels: pr(documentation)

#3716 fix(umi-ui): antd 4.0 icon using outline & Grid bug
  docs/guide/develop-umi-ui-plugin.md
  docs/zh/guide/develop-umi-ui-plugin.md
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/ui/client/Adder/InfoToolTip.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/AssetsMenu/index.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/BlockList/BlockItem.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/BlockList/ImagePreview.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/BlocksViewer.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/GlobalSearch.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/LogPanel/index.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/TagSelect/index.tsx
  packages/umi-build-dev/yarn.lock
  packages/umi-plugin-ui/package.json
  packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/action.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
  packages/umi-plugin-ui/yarn.lock
  packages/umi-types/ui.d.ts
  packages/umi-ui-tasks/package.json
  packages/umi-ui-tasks/src/ui.tsx
  packages/umi-ui-tasks/src/ui/components/Analyze/index.tsx
  packages/umi-ui-tasks/src/ui/components/Build/index.tsx
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
  packages/umi-ui-tasks/src/ui/components/Install/index.tsx
  packages/umi-ui-tasks/src/ui/components/Lint/index.tsx
  packages/umi-ui-tasks/src/ui/components/Terminal/index.tsx
  packages/umi-ui-tasks/src/ui/components/Test/index.tsx
  packages/umi-ui-tasks/yarn.lock
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/components/ConfigForm/index.tsx
  packages/umi-ui/client/src/components/DirectoryForm/index.tsx
  packages/umi-ui/client/src/components/DirectoryForm/item.tsx
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
  packages/umi-ui/client/src/components/Field/Any.tsx
  packages/umi-ui/client/src/components/Field/StringArray.tsx
  packages/umi-ui/client/src/components/Field/fields/ObjectField.tsx
  packages/umi-ui/client/src/components/Field/fields/ObjectItemField.tsx
  packages/umi-ui/client/src/components/Terminal/index.tsx
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/FooterToolbar.tsx
  packages/umi-ui/client/src/pages/loading/fail.tsx
  packages/umi-ui/client/src/pages/project/components/create/Form2.tsx
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/package.json
  packages/umi-ui/yarn.lock
  yarn.lock
Labels: pr(bug)

#3723 fix(af-webpack): stats undefined when have error
  packages/af-webpack/src/build.js
Labels: pr(bug)

#3724 feat: use @@ instead of @tmp
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-build-dev/template/router.js.tpl
  packages/umi/.fatherrc.js
  packages/umi/index.d.ts
  packages/umi/src/index.js
  packages/umi/src/router.js
Labels: pr(enhancement)
