Repository umijs/umi, pull requests merged in 2019-10, with the labels that each got.

#3351 docs: detail usage about locales
  docs/api/README.md
  docs/zh/api/README.md
Labels: pr(documentation)

#3291 feat: depth first init plugins
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/Service.test.js
Labels: pr(enhancement)

#3393 fix: disable dev ui mini in ssr
  packages/umi/src/isUmiUIEnable.js
Labels: pr(bug), type(ssr)

#3404 fix(umi-ui): dva detection failed in bigfish
  packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts
Labels: pr(bug)

#3401 fix: Umi mini url using host not domain in iframe
  packages/umi-plugin-ui/src/bubble/index.jsx
Labels: pkg(umi-ui), pr(bug)

#3405 feat(umi-ui): allow to specify detect language with DETECT_LANGUAGE env
  packages/umi-ui/src/detectLanguage.ts
Labels: pr(enhancement)

#3407 tweak: mini tips when access using remote ip
  packages/umi-plugin-ui/src/bubble/Error.jsx
  packages/umi-plugin-ui/src/bubble/bubble-locale/en-US.js
  packages/umi-plugin-ui/src/bubble/bubble-locale/pt-BR.js
  packages/umi-plugin-ui/src/bubble/bubble-locale/zh-CN.js
  packages/umi-plugin-ui/src/bubble/bubble-locale/zh-TW.js
  packages/umi-plugin-ui/src/bubble/index.jsx
Labels: pkg(umi-ui), pr(enhancement)

#3410 fix: generate file only when file content changes
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/utils/writeContent.js
Labels: pr(bug)

#3416 fix(umi-ui): don't throw error if return statement not found
  packages/umi-build-dev/src/plugins/commands/block/sdk/util.ts
Labels: pr(bug)

#3420 docs: umi ui plugin dev peerDeps
  docs/.vuepress/styles/palette.styl
  docs/guide/develop-umi-ui-plugin.md
  docs/zh/guide/develop-umi-ui-plugin.md
Labels: pr(documentation)

#3419 chore(umi-ui): remove preview button
  packages/umi-build-dev/src/plugins/commands/block/ui/ui/Adder/ResultPanel.tsx
Labels: pkg(umi-ui), pr(chore)

#3423 tweak: umi ui code format & windows ci
  azure-pipelines.yml
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/sdk/insertComponent/index.test.ts
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/client/src/utils/index.tsx
  packages/umi-ui/src/Config.test.ts
  packages/umi/test/build.e2e.ts
  packages/umi/test/dev.e2e.js
  packages/umi/test/ui.e2e.ts
Labels: pr(chore)

#3418 feat(umi-ui): better router get
  packages/umi-build-dev/src/plugins/commands/block/__snapshots__/util.test.ts.snap
  packages/umi-build-dev/src/plugins/commands/block/arrayToTree.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/core/Block.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/index.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/ui/index.module.less
  packages/umi-build-dev/src/plugins/commands/block/util.test.ts
  packages/umi-build-dev/src/plugins/commands/block/util.ts
  packages/umi-build-dev/src/plugins/fixtures/util/routerConfig.js
Labels: pr(enhancement)

#3427 tweak: umi ui css modules types
  .gitignore
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/src/typings/exclude.d.ts
Labels: pkg(umi-ui-theme), pr(chore)

#3424 fix: umi ui showMini,hideMini api condition
  packages/umi-ui/client/src/PluginAPI.ts
Labels: pkg(umi-ui), pr(bug)

#3431 dep: revert webpack-dev-server to 3.2.1
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: pr(dependency)

#3433 fix: get config failed with UMI_ENV and .umirc.{UMI_ENV}.js
  packages/umi-core/src/registerBabel.ts
Labels: pr(bug)

#3439 chore: ui build script OOM
  scripts/ui.js
Labels: pkg(umi-ui), pr(chore)

#3440 fix(umi-ui): loading page error
  packages/umi-plugin-ui/yarn.lock
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/pages/loading/index.tsx
  packages/umi-ui/client/src/services/project.ts
  packages/umi-ui/client/src/utils/index.tsx
  packages/umi-ui/src/Config.ts
  packages/umi-ui/src/UmiUI.ts
Labels: pkg(umi-ui), pr(bug)

#3436 fix(umi-ui): error message is readOnly object
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
Labels: pkg(umi-ui), pr(bug)

#3444 fix(umi-ui): check valid before list project
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/src/Config.ts
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3451 fix(umi-ui): bubble syntax error in IE
  jest.config.js
  package.json
  packages/af-webpack/src/patchConnection.js
  packages/umi-build-dev/.fatherrc.js
  packages/umi-plugin-ui/.fatherrc.js
  packages/umi-ui-tasks/.fatherrc.js
  yarn.lock
Labels: pr(bug)

#3454 docs(umi-ui): fix bigfish help doc link
  packages/umi-ui/client/src/layouts/Footer.tsx
Labels: pr(bug)

#3455 fix(umi-ui): don't show umi ui bubble in IE
  packages/umi-plugin-ui/.fatherrc.js
  packages/umi-plugin-ui/src/index.ts
Labels: pr(bug)

#3447 feat(umi-server): server runtime render tool for Umi SSR
  azure-pipelines.yml
  jest.config.js
  packages/umi-server/.fatherrc.ts
  packages/umi-server/README.md
  packages/umi-server/bin/umi-server.js
  packages/umi-server/index.js
  packages/umi-server/package.json
  packages/umi-server/src/compose.ts
  packages/umi-server/src/index.ts
  packages/umi-server/src/utils.ts
  packages/umi-server/test/__snapshots__/index.test.ts.snap
  packages/umi-server/test/fixtures/ssr-dynamicImport/.umirc.js
  packages/umi-server/test/fixtures/ssr-dynamicImport/models/count.js
  packages/umi-server/test/fixtures/ssr-dynamicImport/pages/index.js
  packages/umi-server/test/fixtures/ssr-dynamicImport/pages/locale.js
  packages/umi-server/test/fixtures/ssr-dynamicImport/pages/news/$id.js
  packages/umi-server/test/fixtures/ssr-styles/.umirc.js
  packages/umi-server/test/fixtures/ssr-styles/pacakge.json
  packages/umi-server/test/fixtures/ssr-styles/pages/index.js
  packages/umi-server/test/fixtures/ssr-styles/pages/index.module.less
  packages/umi-server/test/fixtures/ssr-styles/pages/news.js
  packages/umi-server/test/fixtures/ssr-styles/pages/news.less
  packages/umi-server/test/fixtures/ssr/.umirc.js
  packages/umi-server/test/fixtures/ssr/models/count.js
  packages/umi-server/test/fixtures/ssr/pages/index.js
  packages/umi-server/test/fixtures/ssr/pages/locale.js
  packages/umi-server/test/fixtures/ssr/pages/news/$id.js
  packages/umi-server/test/index.test.ts
  packages/umi-server/tsconfig.json
  packages/umi-server/yarn.lock
  packages/umi/test/build.e2e.ts
  packages/umi/test/dev.e2e.js
  packages/umi/test/fixtures/build/ssr/test.js
  packages/umi/test/fixtures/dev/ssr/.umirc.js
  packages/umi/test/fixtures/dev/ssr/pacakge.json
  scripts/antd-pro.sh
  scripts/startDevServers.js
  yarn.lock
Labels: pr(enhancement), type(ssr)

#3458 fix(umi-ui): add blacklist root node including antd and tech-ui
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-card/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-card/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-step/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-antd-step/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-PageContainer/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-PageContainer/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-StepForm/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-tech-ui-StepForm/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
Labels: pr(bug)

#3456 docs: minor formatting errors
  docs/zh/config/README.md
Labels: pr(documentation)

#3463 fix(umi-plugin-ui): bubble client height 0 when body, html not set
  packages/umi-plugin-ui/src/bubble/utils.js
Labels: pkg(umi-plugin-ui), pr(bug)

#3465 fix: extraBabelIncludes merge problem between config and plugin
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
Labels: pr(bug)

#3470 chore: mv loadDotEnv to umi-utils
  packages/umi-build-dev/src/Service.js
  packages/umi-utils/package.json
  packages/umi-utils/src/fixtures/loadDotEnv/.env
  packages/umi-utils/src/index.d.ts
  packages/umi-utils/src/index.ts
  packages/umi-utils/src/loadDotEnv.test.ts
  packages/umi-utils/src/loadDotEnv.ts
  packages/umi-utils/yarn.lock
  packages/umi/src/buildDevOpts.js
Labels: pr(chore)

#3476 feat: add env config: USE_PUBLIC_IP to bind public ip
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/prepareUrls.js
Labels: pr(enhancement)

#3477 fix(umi-ui): fix source undefined in flagBabelPlugin
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-not-import/expected.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/fixtures/root-blacklist-not-import/origin.js
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
Labels: pr(bug)

#3353 feat: upgrade react-router to 5
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
Labels: pr(enhancement)

#3491 fix: ssr build target should using node env
  packages/umi-build-dev/src/getWebpackConfig.ts
Labels: pr(bug), type(ssr)

#3492 chore: remove travis, using circle
  .codecov.yml
  .travis.yml
  README.md
  circle.yml
  lerna.json
Labels: pr(chore)

#3504 doc: 添加社区例子 umi-dva-antd-mobile
  docs/zh/guide/examples.md
Labels: pr(documentation)

#3515 fix: umi-types xterm types
  packages/umi-types/package.json
Labels: pr(bug)

#3521 feat: use esm version of history
  packages/umi-build-dev/src/plugins/history.js
  packages/umi/src/createHistory.js
Labels: pr(enhancement)

#3520 fix(umi-ui): usage of @alipay/bigfish/antd
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/index.ts
Labels: pr(bug)

#3489 refactor: support Basic UI extend using modifyBasicUI for Bigfish
  docs/plugin/umi-ui.md
  docs/zh/plugin/umi-ui.md
  jest.config.js
  package.json
  packages/umi-build-dev/src/plugins/history.js
  packages/umi-plugin-ui/src/plugins/configuration/ui.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/index.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
  packages/umi-types/index.d.ts
  packages/umi-types/ui.d.ts
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/client/src/components/DirectoryForm/index.tsx
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
  packages/umi-ui/client/src/components/StepForm/StepForm.tsx
  packages/umi-ui/client/src/components/StepForm/StepItem.tsx
  packages/umi-ui/client/src/components/StepForm/index.tsx
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/layouts/Project.tsx
  packages/umi-ui/client/src/message.ts
  packages/umi-ui/client/src/pages/project/components/create/Form1.tsx
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
  packages/umi-ui/client/src/pages/project/index.tsx
  packages/umi-ui/client/src/typings/global.d.ts
  packages/umi-ui/client/src/utils/index.test.tsx
  packages/umi-ui/client/src/utils/index.tsx
  packages/umi-ui/client/src/utils/isValid.ts
  packages/umi-ui/package.json
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/src/getClientScript.ts
  packages/umi-ui/ui/.fatherrc.ts
  packages/umi-ui/ui/components/logo.tsx
  packages/umi-ui/ui/global.d.ts
  packages/umi-ui/ui/package.json
  packages/umi-ui/ui/tsconfig.json
  packages/umi-ui/ui/ui.tsx
  packages/umi/_umiUI.js
  packages/umi/src/createHistory.js
  scripts/publish.js
  scripts/ui.js
  scripts/uiPlugins.js
Labels: pr(chore), pr(enhancement)

#3483 feat(stylus): 添加stylus支持
  packages/af-webpack/package.json
  packages/af-webpack/src/getUserConfig/configs/stylus.js
  packages/af-webpack/src/getWebpackConfig/css.js
  packages/af-webpack/src/getWebpackConfig/index.js
  packages/af-webpack/test/fixtures/stylus/expected/index.css
  packages/af-webpack/test/fixtures/stylus/expected/index.js
  packages/af-webpack/test/fixtures/stylus/index.js
  packages/af-webpack/test/fixtures/stylus/index.styl
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-build-dev/src/plugins/global-css.js
Labels: pr(enhancement)

#2963 docs: ssr
  docs/.vuepress/config.js
  docs/.vuepress/styles/index.styl
  docs/api/README.md
  docs/guide/faq.md
  docs/guide/pre-render.md
  docs/guide/ssr.md
  docs/zh/api/README.md
  docs/zh/guide/faq.md
  docs/zh/guide/pre-render.md
  docs/zh/guide/ssr.md
  website/package.json
Labels: pr(documentation)

#3538 fix(umi-ui): plugin exec error hanlder
  packages/umi-ui/src/getClientScript.ts
Labels: pkg(umi-ui), pr(bug)
