Repository umijs/umi, pull requests merged in 2019-05, with the labels that each got.

#2363 fix: ci broken since docz's upgrade
  packages/af-webpack/yarn.lock
  packages/eslint-config-umi/yarn.lock
  packages/umi-library/package.json
  packages/umi-library/src/doc.e2e.ts
  packages/umi-library/yarn.lock
  packages/umi-plugin-auto-externals/yarn.lock
  packages/umi-plugin-dva/yarn.lock
  packages/umi-test/yarn.lock
Labels: pr(bug)

#2351 fix(umi-library): theme path problem in windows
  packages/umi-library/src/doczrc.ts
Labels: pr(bug)

#2369 docs: umi test
  docs/guide/getting-started.md
  docs/zh/guide/getting-started.md
Labels: pr(documentation)

#2340 feat: delete global variables includes g_history, g_plugins, g_routes and g_app
  jest.config.js
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/getConfig/configPlugins/disableGlobalVariables.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-build-dev/template/history.js.tpl
  packages/umi-build-dev/template/router.js.tpl
  packages/umi-plugin-dva/src/index.js
  packages/umi-plugin-dva/src/runtime.js
  packages/umi-plugin-dva/template/DvaContainer.js
  packages/umi-plugin-dva/template/dva.js.tpl
  packages/umi-plugin-dva/template/initDva.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi/src/renderRoutes.js
  packages/umi/src/renderRoutes.test.js
  packages/umi/src/router.js
  packages/umi/test/fixtures/build/runtime-plugins/app.js
  packages/umi/test/fixtures/build/runtime-plugins/pages/index.css
  packages/umi/test/fixtures/build/runtime-plugins/pages/index.js
  packages/umi/test/fixtures/build/runtime-plugins/test.js
  packages/umi/test/fixtures/e2e/hashHistory/.umirc.js
  packages/umi/test/fixtures/e2e/hashHistory/README.md
  packages/umi/test/fixtures/e2e/hashHistory/pacakge.json
  packages/umi/test/fixtures/e2e/hashHistory/pages/list.js
  packages/umi/test/hashHistory.e2e.js
  packages/umi/test/runtime/package.json
  scripts/startDevServers.js
Labels: pr(enhancement)

#2377 dep: upgrade react and react-dom to 16.8.6
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi/test/fixtures/build/auto-external/test.js
Labels: pr(dependency)

#2387 feat(umi-library): generate declaration for babel mode
  .prettierignore
  packages/umi-library/package.json
  packages/umi-library/src/babel.ts
  packages/umi-library/src/fixtures/build/babel-typescript/.umirc.library.js
  packages/umi-library/src/fixtures/build/babel-typescript/expected/es/index.d.ts
  packages/umi-library/src/fixtures/build/babel-typescript/expected/es/index.js
  packages/umi-library/src/fixtures/build/babel-typescript/expected/lib/index.d.ts
  packages/umi-library/src/fixtures/build/babel-typescript/expected/lib/index.js
  packages/umi-library/src/fixtures/build/babel-typescript/src/index.ts
  packages/umi-library/src/fixtures/build/babel-typescript/tsconfig.json
  packages/umi-library/yarn.lock
Labels: pr(enhancement)

#2309 dep: upgrade js-yaml to 3.13.1
  packages/umi-build-dev/package.json
Labels: pr(dependency)

#2355 New setLang function
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/src/locale.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
Labels: pr(enhancement)

#2411 chore: remove esprima and use babal parser for block wirte routes
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.result.js
  packages/umi-build-dev/src/utils/fixtures/exportDefaultRoutes.resultWithLayout.js
  packages/umi-build-dev/src/utils/fixtures/exportsRoutes.result.js
  packages/umi-build-dev/src/utils/fixtures/exportsRoutes.resultWithLayout.js
  packages/umi-build-dev/src/utils/fixtures/importedRoutes.result.js
  packages/umi-build-dev/src/utils/fixtures/importedRoutes.resultWithLayout.js
  packages/umi-build-dev/src/utils/fixtures/routeNode.json
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
Labels: pr(chore)

#2410 fix(umi-types): lost definitions for api.writeTmpFile and config.disableGlobalVariabls
  packages/umi-types/config.d.ts
  packages/umi-types/index.d.ts
Labels: pr(bug)

#2416 feat(umi-plugin-react): support use string[] in scripts and headScripts configuration
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/plugins/headScripts.js
  packages/umi-plugin-react/src/plugins/headScripts.ts
  packages/umi-plugin-react/src/plugins/scripts.js
  packages/umi-plugin-react/src/plugins/scripts.ts
  packages/umi-plugin-react/src/utils/getScripts.test.js
  packages/umi-plugin-react/src/utils/getScripts.ts
Labels: pkg(umi-plugin-react)

#2417 fix: addUmiExports error in hmr
  packages/umi-build-dev/src/plugins/importFromUmi.js
  packages/umi-types/index.d.ts
Labels: pr(bug)

#2423 doc: fix uglifyJSOptions e.g.
  docs/config/README.md
  docs/zh/config/README.md
Labels: pr(documentation)

#2429 fix: umi-build-dev add esprima-extract-comments denpendency
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  yarn.lock
Labels: pr(bug)

#2430 feat: export router in @tmp/router
  packages/umi-build-dev/template/router.js.tpl
Labels: pr(enhancement)

#2311 feature: umi block v2
  docs/zh/guide/block.md
  packages/umi-build-dev/src/fixtures/block/antdpro/package.json
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo-with-dependencies/package.json
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo-with-dependencies/src/index.js
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo-with-dependencies/src/index.less
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo/package.json
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo/src/index.js
  packages/umi-build-dev/src/fixtures/block/test-blocks/demo/src/index.less
  packages/umi-build-dev/src/getPaths.js
  packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.test.js
  packages/umi-build-dev/src/plugins/commands/block/getConstVarsFromPath.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/index.test.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
  packages/umi-build-dev/template/blockEntry.js.tpl
Labels: pr(enhancement)

#2435 feat: support add new route to typescript config when add a block
  packages/umi-build-dev/src/fixtures/block/antdpro/pages/index.js
  packages/umi-build-dev/src/plugins/commands/block/appendBlockToContainer.js
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/index.test.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
  packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.result.ts
  packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.resultWithLayout.ts
  packages/umi-build-dev/src/utils/fixtures/routesWithTypescript.ts
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
Labels: pr(enhancement)

#2443 fix(umi-test): jest 兼容 tnpm 目录结构的正则表达式
  packages/umi-test/src/index.js
Labels: pr(bug)

#2445 fix: misspell
  packages/umi-plugin-locale/src/locale.js
Labels: pr(documentation)

#2452 feat: support cssLoaderVersion config
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/src/getUserConfig/configs/cssLoaderVersion.js
  packages/af-webpack/yarn.lock
  packages/umi-types/config.d.ts
Labels: pr(enhancement)

#2457 deps: upgrade uglify-webpack-plugin to 2.1.3
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: pr(dependency)

#2440 doc: add intro for `umi:command not found`
  docs/zh/guide/getting-started.md
Labels: pr(documentation)

#2459 fix: the basename of router should be kept while the history mode is hash
  packages/umi-build-dev/src/plugins/history.js
Labels: pr(bug)

#2461 doc: fix technical terms
  README.md
Labels: pr(documentation)

#2462 fix: remove not be supported settings
  docs/config/README.md
  docs/zh/config/README.md
  packages/af-webpack/src/getConfig/uglifyOptions.js
Labels: pr(bug)

#2470 dep: upgrade webpack-bundle-anaylze for vulnerability
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: pr(dependency)

#2463 docs: typo in description of pwa option
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
Labels: pr(documentation)

#2468 feat: block support --layout and config npmClient
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/index.test.js
Labels: pr(enhancement)

#2469 feat: locale intellisense
  packages/umi-plugin-locale/index.d.ts
Labels: pr(enhancement)

#2478 fix: insert new block element in redirect return function
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.test.js
Labels: pr(bug)

#2485 fix: Uglify-js update lead to fail in build
  packages/af-webpack/src/getConfig/uglifyOptions.js
Labels: pr(bug)

#2486 fix(umi-plugin-dll): ignore @types packages
  packages/umi-plugin-dll/src/buildDll.js
Labels: pr(bug)

#2488 fix: Uglify-js option
  packages/af-webpack/src/getConfig/uglifyOptions.js
Labels: pr(bug)

#2497 fix(umi-library): don't exit process when compile failed with babel type
  packages/umi-library/src/babel.ts
Labels: pr(bug)

#2143 fix: same reference to common route config will lead to wrong path
  packages/umi-build-dev/src/routes/getRouteConfigFromConfig.js
  packages/umi-build-dev/src/routes/getRouteConfigFromConfig.test.js
Labels: pr(bug)

#2498 fix(umi-plugin-hd): theme failed with theme file
  packages/umi-plugin-hd/src/index.js
Labels: pr(bug)
