Repository umijs/umi, pull requests merged in 2019-09, with the labels that each got.

#3110 fix: UmiUI empty paddingTop & umi ci test
  .travis.yml
  azure-pipelines.yml
  circle.yml
  package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-ui-tasks/yarn.lock
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
  scripts/test.js
  yarn.lock
Labels: pr(enhancement)

#3115 fix(umi-ui): failed when OPEN_PROJECT run multiple times
  packages/umi-ui/src/Config.ts
Labels: pr(bug)

#3114 fix(umi-ui): improvements
  package.json
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/project/components/list/index.less
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/client/src/styles/parameters.less
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3113 feat(umi-ui): add mac address
  packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
  packages/umi-plugin-ui/src/plugins/dashboard/ui/ui.module.less
  packages/umi-ui-tasks/src/locales/en-US.js
  packages/umi-ui-tasks/src/locales/zh-CN.js
  packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts
  packages/umi-ui-tasks/src/ui.tsx
  packages/umi-ui-tasks/src/ui/components/Build/index.tsx
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
  packages/umi-ui-tasks/src/ui/util/terminal.ts
  packages/umi-ui/client/src/components/Terminal/index.tsx
  packages/umi-ui/package.json
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/src/scripts.ts
Labels: pr(enhancement)

#3116 doc(umi-ui): move API.md to umijs.org
  docs/.vuepress/config.js
  docs/plugin/umi-ui.md
  docs/zh/plugin/umi-ui.md
Labels: pr(documentation)

#3117 docs: umi UI api, feat: getCwd
  docs/plugin/umi-ui.md
  docs/zh/plugin/umi-ui.md
  packages/umi-types/ui.d.ts
  packages/umi-ui/client/src/PluginAPI.ts
Labels: pr(documentation)

#3119 fix: umi/_Service lost when publish to npm
  packages/umi/package.json
Labels: pr(bug)

#3120 fix(umi-ui): Umi 版本过低后刷新有效
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/src/utils/isDepFileExists.ts
Labels: pr(bug)

#3121 fix(umi-ui): qrcode
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3118 fix: notify api not pass type
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/PluginAPI.ts
Labels: pr(bug)

#3123 fix: Umi UI BasicConfig targets validator
  packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/Object.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/ObjectField.tsx
  packages/umi-ui/client/src/layouts/Layout.tsx
  packages/umi-ui/client/src/locales/en-US.ts
Labels: pr(bug)

#3122 feat(umi-ui): list page icons
  packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/dashboard/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
  packages/umi-ui/client/src/assets/code.svg
  packages/umi-ui/client/src/pages/project/components/list/index.less
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
Labels: pr(enhancement)

#3126 fix(umi-ui): version print, publicPath validate and doc
  docs/.vuepress/config.js
  docs/guide/umi-ui.md
  docs/zh/guide/umi-ui.md
  packages/af-webpack/src/getUserConfig/configs/publicPath.js
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3124 fix(umi-ui): ui details
  packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/ObjectField.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/fields/styles.module.less
  packages/umi-ui-tasks/src/locales/en-US.js
  packages/umi-ui-tasks/src/locales/zh-CN.js
  packages/umi-ui-tasks/src/ui/components/Terminal/index.tsx
  packages/umi-ui-tasks/src/ui/ui.module.less
  packages/umi-ui/client/src/components/DirectoryForm/index.less
  packages/umi-ui/client/src/components/DirectoryForm/index.tsx
  packages/umi-ui/client/src/global.less
  packages/umi-ui/client/src/layouts/Footer.less
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/project/components/create/Form2.tsx
  packages/umi-ui/client/src/pages/project/components/list/index.less
  packages/umi-ui/client/src/styles/parameters.less
Labels: pr(bug)

#3127 fix(umi-ui): add umi & bigfish version
  packages/umi-plugin-ui/src/plugins/dashboard/locales/en-US.ts
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
  packages/umi-ui/client/src/layouts/Footer.less
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/src/scripts.ts
Labels: pr(enhancement)

#3128 fix(umi-ui): bigfish logo style
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/project/components/list/index.less
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
Labels: pr(bug)

#3129 docs ui plugin guide
  docs/.vuepress/config.js
  docs/guide/develop-umi-ui-plugin.md
  docs/guide/ui-plugin.md
  docs/zh/guide/block.md
  docs/zh/guide/develop-umi-ui-plugin.md
Labels: pr(documentation)

#3132 fix: umi help info for umi ui
  packages/umi-build-dev/src/plugins/commands/help.js
Labels: pr(bug)

#3134 fix(block): remoteLog undefined
  packages/umi-build-dev/src/plugins/commands/block/index.js
Labels: pr(bug)

#3136 fix: original error stack should be preferred
  packages/umi-build-dev/src/UserConfig.js
Labels: pr(bug)

#3111 chore: create ci.yml
  .github/workflows/ci.yml
  .travis.yml
  README.md
  azure-pipelines.yml
  circle.yml
  package.json
  packages/umi/test/dev.e2e.js
  scripts/test.js
  yarn.lock
Labels: pr(chore)

#3142 fix(umi-ui): add reinstall button when umi's version unmatch
  packages/umi-ui/client/src/pages/loading/index.tsx
  packages/umi-ui/src/UmiUI.ts
Labels: pr(bug)

#3137 fix(umi-ui): create steps locale can't switch
  packages/umi-ui/client/src/enums/index.ts
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/src/UmiUI.ts
Labels: pkg(umi-ui), pr(bug)

#3140 chore: add action ci badge
  README.md
Labels: pr(chore)

#3143 doc(umi-ui): improve tips when local umi's version does not match
  docs/guide/faq.md
  docs/zh/guide/faq.md
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/loading/index.tsx
  packages/umi-ui/src/UmiUI.ts
Labels: pr(documentation)

#3146 fix(umi-ui): hide project create in bigfish
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
Labels: pr(bug)

#3144 doc: umi base ui use antd 4.x to develop
  docs/guide/develop-umi-ui-plugin.md
  docs/zh/guide/develop-umi-ui-plugin.md
Labels: pr(documentation)

#3150 feat: 支持 BASE_PORT 环境变量
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/getPort.js
Labels: pr(enhancement)

#3149 docs: umi-plugin-react docs format
  docs/plugin/umi-plugin-prerender.md
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
Labels: pr(documentation)

#3157 fix(umi-ui): reinstall error
  packages/umi-ui-tasks/src/server/core/Tasks/Install.ts
Labels: pr(bug)

#3154 fix: 获取浏览器语言设置判断出错
  packages/umi-plugin-locale/src/locale.js
Labels: pr(bug)

#3161 fix(Umi UI): permission eror message
  docs/guide/faq.md
  docs/zh/guide/faq.md
  packages/umi-ui/client/src/components/DirectoryForm/index.tsx
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/src/installCreator.ts
  packages/umi-ui/src/npmClient.ts
Labels: pr(bug), type(umi UI)

#3162 fix(Umi UI): reduce client bundle size
  packages/umi-ui/client/.env
Labels: pr(bug), type(umi UI)

#3165 chore: doc preview site
  netlify.toml
  website/package.json
Labels: pr(chore)

#3170 feat(umi-ui): form config api.Field
  docs/plugin/umi-ui.md
  docs/zh/plugin/umi-ui.md
  packages/umi-plugin-ui/src/plugins/configuration/locales/en-US.ts
  packages/umi-plugin-ui/src/plugins/configuration/locales/zh-CN.ts
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/BasicConfig.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/Any.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/index.tsx
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/ConfigItem/utils.ts
  packages/umi-plugin-ui/src/plugins/configuration/ui/components/utils.ts
  packages/umi-types/ui.d.ts
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/client/src/components/Field/Any.tsx
  packages/umi-ui/client/src/components/Field/Boolean.tsx
  packages/umi-ui/client/src/components/Field/List.tsx
  packages/umi-ui/client/src/components/Field/Object.tsx
  packages/umi-ui/client/src/components/Field/ObjectArray.tsx
  packages/umi-ui/client/src/components/Field/String.tsx
  packages/umi-ui/client/src/components/Field/StringArray.tsx
  packages/umi-ui/client/src/components/Field/TextArea.tsx
  packages/umi-ui/client/src/components/Field/fields/ObjectField.tsx
  packages/umi-ui/client/src/components/Field/fields/ObjectItemField.tsx
  packages/umi-ui/client/src/components/Field/fields/styles.module.less
  packages/umi-ui/client/src/components/Field/index.tsx
  packages/umi-ui/client/src/components/Field/label.tsx
  packages/umi-ui/client/src/components/Field/styles.module.less
  packages/umi-ui/client/src/components/Field/utils.ts
  packages/umi-ui/client/src/locales/en-US.ts
  packages/umi-ui/client/src/locales/zh-CN.ts
  packages/umi-ui/client/src/typings/exclude.d.ts
  packages/umi-ui/src/UmiUI.ts
Labels: pkg(umi-ui), pr(enhancement)

#3169 fix: umi-serve console the error message when mock parse error
  packages/umi-mock/src/createMiddleware.js
  packages/umi-serve/bin/umi-serve.js
Labels: pr(bug)

#3172 fix(Umi UI): ga analyse SPA pathname
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/client/src/typings/global.d.ts
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/src/scripts.ts
Labels: pr(chore)

#3171 feat(umi-ui): extract Umi UI dark theme vars
  docs/guide/develop-umi-ui-plugin.md
  docs/zh/guide/develop-umi-ui-plugin.md
  docs/zh/plugin/umi-ui.md
  packages/umi-ui-theme/.fatherrc.ts
  packages/umi-ui-theme/README.md
  packages/umi-ui-theme/dark.less
  packages/umi-ui-theme/light.less
  packages/umi-ui-theme/package.json
  packages/umi-ui-theme/src/index.ts
  packages/umi-ui-theme/test/index.test.ts
  packages/umi-ui-theme/yarn.lock
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/styles/parameters.less
  packages/umi-ui/client/src/styles/theme.js
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/package.json
  packages/umi-ui/yarn.lock
Labels: pkg(umi-ui), pr(enhancement)

#3176 chore: fix father-build failed since babel@7.6
  packages/babel-preset-umi/src/index.test.js
  packages/umi-utils/src/findCSS.js
  packages/umi-utils/src/findJS.js
Labels: pr(chore)

#3181 feat(umi-ui): support dva, add api.registerModel, api.connect
  packages/umi-types/package.json
  packages/umi-types/ui.d.ts
  packages/umi-types/yarn.lock
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/package.json
Labels: pr(enhancement)

#3177 fix: umi ui deer analyse
  packages/umi-ui/client/src/typings/global.d.ts
  packages/umi-ui/src/scripts.ts
Labels: pr(bug), type(umi UI)

#3178 fix: IBeforeDevServerFunc and IAfterDevServerFunc type errors
  packages/umi-types/index.d.ts
Labels: pr(bug)

#3188 chore: convert umi-utils to TypeScript
  packages/umi-utils/package.json
  packages/umi-utils/src/chunkName.test.js
  packages/umi-utils/src/chunkName.test.ts
  packages/umi-utils/src/chunkName.ts
  packages/umi-utils/src/compatDirname.test.js
  packages/umi-utils/src/compatDirname.test.ts
  packages/umi-utils/src/compatDirname.ts
  packages/umi-utils/src/deprecate.ts
  packages/umi-utils/src/endWithSlash.js
  packages/umi-utils/src/endWithSlash.test.js
  packages/umi-utils/src/endWithSlash.test.ts
  packages/umi-utils/src/endWithSlash.ts
  packages/umi-utils/src/findCSS.test.js
  packages/umi-utils/src/findCSS.test.ts
  packages/umi-utils/src/findCSS.ts
  packages/umi-utils/src/findJS.test.js
  packages/umi-utils/src/findJS.test.ts
  packages/umi-utils/src/findJS.ts
  packages/umi-utils/src/getFastGithub.ts
  packages/umi-utils/src/index.d.ts
  packages/umi-utils/src/index.ts
  packages/umi-utils/src/isUrl.js
  packages/umi-utils/src/isUrl.test.js
  packages/umi-utils/src/isUrl.test.ts
  packages/umi-utils/src/isUrl.ts
  packages/umi-utils/src/optsToArray.js
  packages/umi-utils/src/optsToArray.test.ts
  packages/umi-utils/src/optsToArray.ts
  packages/umi-utils/src/prettierFile.test.ts
  packages/umi-utils/src/prettierFile.ts
  packages/umi-utils/src/winEOL.test.ts
  packages/umi-utils/src/winEOL.ts
  packages/umi-utils/src/winPath.js
  packages/umi-utils/src/winPath.test.ts
  packages/umi-utils/src/winPath.ts
Labels: pr(chore)

#3187 doc: add tsx extension to module list
  docs/guide/module-processor.md
Labels: pr(documentation)

#3191 feat(umi ui): table less theme
  packages/umi-ui-theme/dark.less
  packages/umi-ui-theme/test/index.test.ts
Labels: pkg(umi-ui-theme), pr(enhancement)

#3194 chore: improve test coverage
  CONTRIBUTING.md
  jest.config.js
  package.json
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/yarn.lock
  packages/umi-build-dev/yarn.lock
  packages/umi-mock/src/createMiddleware.test.js
  packages/umi-mock/src/fixtures/createMiddleware/mock/a.js
  packages/umi-mock/src/fixtures/createMiddleware/pages/.gitkeep
  packages/umi-mock/src/fixtures/parse-failed/mock/error.js
  packages/umi-mock/src/getMockData.test.js
  packages/umi-plugin-auto-externals/yarn.lock
  packages/umi-plugin-dva/yarn.lock
  packages/umi-plugin-react/yarn.lock
  packages/umi-plugin-ui/yarn.lock
  packages/umi-serve/yarn.lock
  packages/umi-test/yarn.lock
  packages/umi-types/yarn.lock
  packages/umi-ui-tasks/yarn.lock
  packages/umi-ui-theme/yarn.lock
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/yarn.lock
  packages/umi/yarn.lock
  yarn.lock
Labels: pr(chore)

#3198 fix(Umi UI): TwoColumnPanel rerender
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
Labels: pkg(umi-ui), pr(bug)

#3199 fix(Umi UI): task ui remove icon-lite deps
  packages/umi-ui-tasks/package.json
  packages/umi-ui-tasks/src/server/core/Tasks/Base.ts
  packages/umi-ui-tasks/src/server/core/Tasks/Dev.ts
Labels: pr(bug)

#3208 feat(plugin): add api.getRoutes for the latest routes
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/Service.test.js
  packages/umi-build-dev/src/fixtures/Service/get-routes/pages/index.js
  packages/umi-types/index.d.ts
Labels: pr(enhancement)

#3207 fix(umi-ui): plugin use promise error
  packages/umi-ui/package.json
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/yarn.lock
Labels: pkg(umi-ui), pr(bug)

#3209 fix: react 15 error when using umi-plugin-locale
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-locale/src/locale.js
  packages/umi-plugin-locale/yarn.lock
Labels: pkg(umi-plugin-locale), pr(bug)

#3216 fix: BABEL_POLYFILL env is allowed to set to none in plugin
  packages/umi-build-dev/src/plugins/targets.js
Labels: pr(bug)

#3219 fix(umi-ui): init path redirect in server
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/src/scripts.ts
Labels: pkg(umi-ui)

#3228 fix(Umi UI): prod not show error message
  packages/umi-ui/client/.umirc.ts
Labels: pkg(umi-ui), pr(bug)

#3229 fix: ci broken in windows
  package.json
  packages/af-webpack/src/getWebpackConfig/index.test.js
Labels: pr(bug)

#3238 docs: plugin develop docs
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: pr(documentation)

#3236 feat(block): support realy skipDependencies
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
  packages/umi-build-dev/yarn.lock
Labels: pr(enhancement)

#3243 chore: improve test coverage
  jest.config.js
  packages/af-webpack/src/dev.js
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/getConfig/configPlugins/base.js
  packages/umi-build-dev/src/getConfig/configPlugins/chainWebpack.js
  packages/umi-build-dev/src/getConfig/configPlugins/context.js
  packages/umi-build-dev/src/getConfig/configPlugins/disableGlobalVariables.js
  packages/umi-build-dev/src/getConfig/configPlugins/disableRedirectHoist.js
  packages/umi-build-dev/src/getConfig/configPlugins/exportStatic.js
  packages/umi-build-dev/src/getConfig/configPlugins/routes.js
  packages/umi-build-dev/src/getConfig/configPlugins/singular.js
  packages/umi-build-dev/src/getConfig/configPlugins/ssr.js
  packages/umi-build-dev/src/getConfig/fixtures/normal/.gitkeep
  packages/umi-build-dev/src/getConfig/fixtures/normal/foo.js
  packages/umi-build-dev/src/getConfig/test/base.test.js
  packages/umi-build-dev/src/getConfig/test/chainWebpack.test.js
  packages/umi-build-dev/src/getConfig/test/context.test.js
  packages/umi-build-dev/src/getConfig/test/disableGlobalVariables.test.js
  packages/umi-build-dev/src/getConfig/test/disableRedirectHoist.test.js
  packages/umi-build-dev/src/getConfig/test/exportStatic.test.js
  packages/umi-build-dev/src/getConfig/test/outputPath.test.js
  packages/umi-build-dev/src/getConfig/test/plugins.test.js
  packages/umi-build-dev/src/getConfig/test/routes.test.js
  packages/umi-build-dev/src/getConfig/test/runtimePublicPath.test.js
  packages/umi-build-dev/src/getConfig/test/singular.test.js
  packages/umi-build-dev/src/getConfig/test/ssr.test.js
  packages/umi-build-dev/src/getConfig/test/treeShaking.test.js
  packages/umi-build-dev/src/getConfig/watch.js
  packages/umi-build-dev/src/getConfig/watch.test.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/importsToStr.js
  packages/umi-build-dev/src/importsToStr.test.js
  packages/umi-build-dev/src/plugins/base.js
  packages/umi-build-dev/src/plugins/commands/config/fixtures/index/.umirc.js
  packages/umi-build-dev/src/plugins/commands/config/fixtures/setConfig/.gitkeep
  packages/umi-build-dev/src/plugins/commands/config/index.js
  packages/umi-build-dev/src/plugins/commands/config/index.test.js
  packages/umi-build-dev/src/plugins/commands/config/setConfig.test.js
  packages/umi-build-dev/src/plugins/commands/dev/fixtures/normal/pages/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.test.js
  packages/umi-build-dev/src/plugins/commands/generate/fixtures/normal/pages/index.js
  packages/umi-build-dev/src/plugins/commands/generate/index.js
  packages/umi-build-dev/src/plugins/commands/generate/index.test.js
  packages/umi-build-dev/src/plugins/fixtures/normal/pages/index.js
  packages/umi-build-dev/template/router.js.tpl
  packages/umi-core/src/fixtures/getUserConfig/cleanConfigRequireCache/.gitkeep
  packages/umi-core/src/fixtures/getUserConfig/cleanConfigRequireCache/.umirc.js
  packages/umi-core/src/fixtures/getUserConfig/getConfigPaths/.umirc.js
  packages/umi-core/src/fixtures/getUserConfig/requireFile/syntaxError.js
  packages/umi-core/src/getUserConfig.test.ts
  packages/umi-core/src/getUserConfig.ts
  packages/umi-test/src/transformers/jsTransformer.js
Labels: pr(chore)

#3245 feat(Umi UI): ui global action support ReactNode
  docs/plugin/umi-ui.md
  docs/zh/plugin/umi-ui.md
  packages/umi-types/ui.d.ts
  packages/umi-ui-theme/test/index.test.ts
  packages/umi-ui/client/src/layouts/Dashboard.tsx
Labels: pkg(umi-ui)

#3247 chore: test Umi UI e2e test
  packages/umi-ui/src/UmiUI.ts
  packages/umi/test/ui.e2e.ts
  scripts/startDevServers.js
  scripts/startUiServers.js
  scripts/test.js
Labels: pkg(umi-ui)

#3250 fix: npm run chore:update-deps error fix
  package.json
Labels: pr(bug)

#3252 fix: import umi-ui fail error
  packages/umi-ui/package.json
Labels: pkg(umi-ui), pr(bug)

#3256 feat(Umi UI): ui bubble error handler
  packages/umi-plugin-ui/bubble/Error.jsx
  packages/umi-plugin-ui/bubble/Loading.jsx
  packages/umi-plugin-ui/bubble/index.jsx
  packages/umi-plugin-ui/bubble/socket.js
  packages/umi-ui-theme/test/index.test.ts
Labels: pkg(umi-ui)

#3261 fix: npm WARN deprecated os-homedir@2.0.0: This is not needed anymore. Use `require(os).homedir()` instead.
  packages/umi-ui/src/Config.ts
  packages/umi-ui/src/installCreator.ts
Labels: pr(bug)

#3275 tweak: auto deploy site using now action
  .github/workflows/deploy-site.yml.bak
  netlify.toml
  now.json
  website/.npmrc
  website/now.json
  website/package.json
Labels: pr(chore)

#3280 fix: ui TwoColumnPanel description error when empty
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
Labels: pkg(umi-ui), pr(bug)

#3279 fix: types
  packages/umi-types/index.d.ts
Labels: pr(chore), type(TypeScript)

#3282 feat: support ERROR_OVERLAY env
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/getWebpackConfig/resolveDefine.js
  packages/af-webpack/src/webpackHotDevClient.js
Labels: pr(enhancement)

#3305 refactor: define IOpts instead.
  packages/umi-ui/src/npmClient.ts
Labels: pr(chore)

#3337 refactor: enhance annotation parsing trouble shooting
  packages/umi-build-dev/src/routes/getRouteConfigFromDir.js
  packages/umi-build-dev/src/routes/getYamlConfig.js
  packages/umi-build-dev/src/routes/getYamlConfig.test.js
Labels: pr(chore)
