Repository umijs/umi, pull requests merged in 2019-04, with the labels that each got.

#2196 docs: translate `src/app.js` in guide/app-structure
  docs/guide/app-structure.md
  docs/zh/guide/app-structure.md
Labels: pr: documentation

#2197 feat(umi-library): support replace config
  packages/umi-library/README.md
  packages/umi-library/src/fixtures/build/rollup-replace/.umirc.library.js
  packages/umi-library/src/fixtures/build/rollup-replace/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-replace/package.json
  packages/umi-library/src/fixtures/build/rollup-replace/src/index.js
  packages/umi-library/src/getRollupConfig.ts
  packages/umi-library/src/schema.ts
  packages/umi-library/src/types.d.ts
Labels: pr: enhancement

#2203 feat(umi-serve): support specify port with PORT env variable
  packages/umi-serve/README.md
  packages/umi-serve/bin/umi-serve.js
Labels: pr: enhancement

#2206 fix(docs): typo
  docs/zh/config/README.md
Labels: pr: documentation

#2205 feat(umi-serve): support for umi-serve Gzip compression.
  packages/umi-serve/bin/umi-serve.js
  packages/umi-serve/package.json
  packages/umi-serve/yarn.lock
Labels: pr: enhancement

#2225 feat(umi-library): support minify esm format with config
  packages/umi-library/README.md
  packages/umi-library/src/fixtures/build/rollup-esm-minify/.umirc.library.js
  packages/umi-library/src/fixtures/build/rollup-esm-minify/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-esm-minify/package.json
  packages/umi-library/src/fixtures/build/rollup-esm-minify/src/foo.js
  packages/umi-library/src/fixtures/build/rollup-esm-minify/src/index.js
  packages/umi-library/src/getRollupConfig.ts
  packages/umi-library/src/schema.ts
  packages/umi-library/src/types.d.ts
Labels: pr: enhancement

#2231 fix(umi-library): docz bin resolve problem
  packages/umi-library/package.json
  packages/umi-library/src/doc.ts
  packages/umi-serve/yarn.lock
Labels: pr: bug

#2234 fix(ui): use `import` for rollup bundle umd files
  packages/umi-build-dev/src/plugins/commands/ui/plugins/blocks/client.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/config/client.js
  packages/umi-build-dev/src/plugins/commands/ui/plugins/routes/client.js
Labels: pr: bug

#2240 fix(umi-library): jsx ext not resolved
  packages/umi-library/src/fixtures/build/rollup-resolve-jsx/.umirc.library.js
  packages/umi-library/src/fixtures/build/rollup-resolve-jsx/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-resolve-jsx/package.json
  packages/umi-library/src/fixtures/build/rollup-resolve-jsx/src/Foo.jsx
  packages/umi-library/src/fixtures/build/rollup-resolve-jsx/src/index.js
  packages/umi-library/src/getRollupConfig.ts
Labels: pr: bug

#2232 feat: support loadingComponent from npm
  packages/umi-plugin-react/src/plugins/dynamicImport.js
  packages/umi-plugin-react/src/utils/isRelativePath.js
  packages/umi-plugin-react/src/utils/isRelativePath.test.js
Labels: pr: enhancement

#2239 test: add winPath.test.js
  jest.config.js
  packages/umi-utils/src/winPath.test.js
Labels: pr: chore

#2242 fix(umi-plugin-dva): dva@2.6-beta don't work
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-dva/src/index.js
  packages/umi-plugin-dva/yarn.lock
  packages/umi/test/fixtures/build/dva/.umirc.js
  packages/umi/test/fixtures/build/dva/models/count.js
  packages/umi/test/fixtures/build/dva/pages/index.js
  packages/umi/test/fixtures/build/dva/test.js
Labels: pr: bug

#2246 fix: revert dva@2.6-beta's fix
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-dva/src/index.js
Labels: pr: bug

#2255 dep: ugprade docz to 1-rc
  packages/umi-library/package.json
  packages/umi-library/src/doc.e2e.ts
  packages/umi-library/src/docz-plugin-react-externals.ts
  packages/umi-library/src/doczrc.ts
  packages/umi-library/yarn.lock
Labels: pr: dependency

#2256 feat(umi-library): docz@1, development version of react, ali cdn
  packages/umi-library/package.json
  packages/umi-library/src/docz-plugin-react-externals.ts
Labels: pr(enhancement)

#2257 feat(umi-library): use docz-theme-umi
  packages/umi-library/package.json
  packages/umi-library/src/doczrc.ts
Labels: pr(enhancement)

#2258 feat(umi-library): support minify cjs
  packages/umi-library/README.md
  packages/umi-library/src/getRollupConfig.ts
  packages/umi-library/src/schema.ts
  packages/umi-library/src/types.d.ts
Labels: pr(enhancement)

#2259 fix(umi-library): docz's alias problem
  packages/umi-library/src/doczrc.ts
Labels: pr(bug)

#2265 fix(umi-library): d.ts should not be tranpiled in babel mode
  packages/umi-library/src/babel.ts
  packages/umi-library/src/fixtures/build/babel-normal/expected/es/types.d.ts
  packages/umi-library/src/fixtures/build/babel-normal/expected/lib/types.d.ts
  packages/umi-library/src/fixtures/build/babel-normal/src/types.d.ts
Labels: pr(bug)

#2267 doc: add some usage about the extraPostCSSPlugins
  docs/config/README.md
  docs/zh/config/README.md
Labels: pr(documentation)

#2270 feat(umi-test): remove jsdom since it's already included in jest
  packages/umi-test/package.json
  packages/umi-test/src/setupTests.js
  packages/umi-test/yarn.lock
Labels: pr(enhancement)

#2273 dep(af-webapck): upgrade mini-css-extract-plugin to 0.6
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/css.js
  packages/af-webpack/yarn.lock
Labels: pr(dependency)

#2274 dep(umi-library): upgrade docz-theme-umi to ^1.1.0
  packages/umi-library/package.json
Labels: pr(dependency)

#2278 chore: add prettier config
  .prettierrc
  package.json
Labels: pr(chore)

#2293 doc: docz config
  packages/umi-library/README.md
Labels: pr(documentation)

#2299 feat(umi-types): config use chainWebpack types
  packages/umi-types/config.d.ts
  packages/umi-types/index.d.ts
Labels: pr(enhancement)

#2301 fix: init history before global.js
  packages/umi-build-dev/template/entry.js.tpl
Labels: pr(bug)

#2310 feat: support extraSetupFiles
  packages/umi-test/src/index.js
Labels: pr(enhancement)

#2314 fix(umi-test): multiple enzyme instance when using tnpm
  packages/umi-test/src/index.js
Labels: pr(bug)

#2316 fix: mock parse error when there are multiple spaces between method a…
  packages/umi-mock/src/fixtures/mock-files/with-method.js
  packages/umi-mock/src/getMockData.js
  packages/umi-mock/src/getMockData.test.js
Labels: pr(bug)

#2321 setDefaultLocal in app.js
  packages/umi-plugin-locale/README.md
  packages/umi-plugin-locale/examples/base/src/app.js
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
Labels: Feature Request, pr(enhancement)
