Repository umijs/umi, pull requests merged in 2019-07, with the labels that each got.

#2731 fix: speed_measure in ssr
  packages/af-webpack/src/getConfig/index.js
Labels: pr(bug)

#2734 feat: support generate webpack stats file
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/getConfig/index.js
Labels: pr(enhancement)

#2735 fix: ssr af-webpack/webpack-dev-middleware
  packages/af-webpack/package.json
Labels: pr(bug)

#2739 docs: add Coverage Badge
  README.md
  README_zh-CN.md
Labels: pr(documentation)

#2744 fix: external whitelist
  packages/umi-build-dev/.fatherrc.js
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-build-dev/yarn.lock
Labels: pr(bug)

#2750 feat: ssr get initial props
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/findRoute.js
  packages/umi-build-dev/src/findRoute.test.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-plugin-dva/src/runtime.js
  packages/umi/src/renderRoutes.js
  packages/umi/test/dev.e2e.js
  packages/umi/test/fixtures/build/ssr/.umirc.js
  packages/umi/test/fixtures/build/ssr/models/count.js
  packages/umi/test/fixtures/build/ssr/pages/index.js
  packages/umi/test/fixtures/build/ssr/test.js
  packages/umi/test/fixtures/dev/ssr/.umirc.js
  packages/umi/test/fixtures/dev/ssr/pacakge.json
  packages/umi/test/fixtures/dev/ssr/src/pages/index.js
  scripts/startDevServers.js
Labels: pr(enhancement)

#2756 feat: umi block clear
  packages/umi-build-dev/src/plugins/commands/block/clearGitCache.js
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
Labels: pr(enhancement)

#2757 fix: jest coveragePath
  jest.config.js
Labels: pr(bug)

#2764 fix: umi locale in ssr, and bug when component not exist
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-plugin-locale/src/locale.js
Labels: pr(bug)

#2765 fix: webpack-chain types
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-types/config.d.ts
  packages/umi-types/index.d.ts
Labels: pr(bug)

#2779 fix: ssr with dynamic router & unnecessary div wrapper
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi/src/renderRoutes.js
  packages/umi/test/fixtures/build/ssr/pages/index.js
  packages/umi/test/fixtures/build/ssr/pages/news/$id.js
  packages/umi/test/fixtures/build/ssr/test.js
Labels: pr(bug)

#2782 dep: upgrade chokidar to 3.0.2, fix warning under windows
  packages/af-webpack/package.json
  packages/umi-build-dev/package.json
  packages/umi-mock/package.json
Labels: pr(bug)

#2788 types: webpack build stats use Array
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-types/index.d.ts
Labels: pr(chore)

#2790 docs: correction of typo
  docs/zh/guide/block.md
Labels: pr(documentation)

#2786 fix: umi ssr locale
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-plugin-locale/src/locale.js
Labels: pr(bug)

#2784 chore: prettier generate file
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-utils/package.json
  packages/umi-utils/src/index.js
  packages/umi-utils/src/prettierFile.js
  packages/umi-utils/src/prettierFile.test.js
  packages/umi-utils/yarn.lock
Labels: pr(chore)

#2811 docs: fix typos
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: pr(documentation)

#2809 feat: support remove i18n code
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/remove-locale.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
  packages/umi-plugin-locale/yarn.lock
  packages/umi/test/build.e2e.ts
  packages/umi/test/fixtures/build/ssr/test.js
Labels: pr(enhancement)

#2812 fix: findRoute recursive bug
  packages/umi-build-dev/src/findRoute.js
  packages/umi-build-dev/src/findRoute.test.js
Labels: pr(bug)

#2802 feat: tweak ssr manifest, not config manifest when use ssr
  docs/config/README.md
  docs/plugin/umi-plugin-prerender.md
  docs/zh/config/README.md
  docs/zh/plugin/umi-plugin-prerender.md
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/Service.test.js
  packages/umi-build-dev/src/fixtures/Service/plugin-ssr/.umirc.js
  packages/umi-build-dev/src/fixtures/Service/plugin-ssr/externalWhitelist/.umirc.js
  packages/umi-build-dev/src/getWebpackConfig.ts
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/getChunkMapPlugin.ts
  packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.js
  packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.test.js
  packages/umi-build-dev/src/plugins/commands/replaceChunkMaps.ts
  packages/umi-build-dev/src/routes/routesToJSON.js
  packages/umi-build-dev/src/utils/getChunkMap.test.js
  packages/umi-build-dev/src/utils/getChunkMap.ts
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-build-dev/test/fixtures/chunkMaps/asset-manifest.json
  packages/umi-build-dev/test/fixtures/chunkMaps/ssr-client-mainifest.json
  packages/umi-build-dev/test/replaceChunkMaps.test.js
  packages/umi-types/config.d.ts
  packages/umi-types/index.d.ts
  packages/umi/test/dev.e2e.js
  packages/umi/test/fixtures/build/ssr/.umirc.js
  packages/umi/test/fixtures/build/ssr/test.js
  packages/umi/test/fixtures/dev/ssr/.umirc.js
  tsconfig.json
Labels: pr(enhancement)

#2829 feat: support auto select fast github
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
  packages/umi-utils/src/getFastGithub.js
  packages/umi-utils/src/index.js
Labels: pr(enhancement)

#2831 dep: webpack@4.36.1
  packages/af-webpack/package.json
  packages/af-webpack/test/fixtures/dynamic-import/.webpackrc
  packages/af-webpack/test/fixtures/dynamic-import/a.js
  packages/af-webpack/test/fixtures/dynamic-import/expected/index.js
  packages/af-webpack/test/fixtures/dynamic-import/expected/page_chunk_a.async.js
  packages/af-webpack/test/fixtures/dynamic-import/index.js
  packages/af-webpack/test/fixtures/json/expected/index.js
  packages/af-webpack/yarn.lock
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/yarn.lock
Labels: pr(dependency)

#2836 chore: add cnpm test ci
  README.md
  circle.yml
  scripts/test.js
Labels: pr(chore)

#2842 fix: umi types
  packages/umi-types/index.d.ts
  packages/umi-types/package.json
  packages/umi-types/yarn.lock
Labels: pr(bug)

#2819 fix: refactoring dva dependencies import
  packages/umi-plugin-dva/src/index.js
Labels: pr(bug)

#2851 fix: node-fetch no found
  packages/umi-utils/package.json
Labels: pr(bug)

#2852 doc: fix word typo
  docs/guide/getting-started.md
Labels: pr(documentation)

#2858 fix: delete spaces before the url
  packages/umi-utils/src/getFastGithub.js
Labels: pr(bug)

#2857 fix: 修复 useLocalStorage 一直为 false 的 bug
  packages/umi-plugin-locale/src/index.js
Labels: pr(bug)

#2861 feat: better fast github
  packages/umi-utils/src/getFastGithub.js
Labels: pr(enhancement)

#2870 url auto add .git
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
Labels: pr(bug), type(block)

#2874 fix: eslint-config-prettier package not found
  packages/umi-build-dev/src/plugins/commands/block/index.js
Labels: pr(bug)

#2882 fix typo
  packages/umi-plugin-modern-mode/README.md
Labels: pr(chore)

#2866 fix(umi-build-dev): unlisten the history listener automatically while app unmount
  packages/umi-build-dev/template/router.js.tpl
Labels: pr(bug)

#2888 fix: module not found for umi dev when global install via cnpm
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
Labels: pr(bug)

#2890 dep: upgrade webpack to 4.38
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/yarn.lock
  packages/umi/bin/umi.js
Labels: pr(dependency)

#2885 fix: 修复windows 平台，Mock文件不能热更新的问题
  packages/umi-mock/package.json
  packages/umi-mock/src/createMiddleware.js
Labels: pr(bug), type(windows)

#2910 fix typo
  docs/zh/guide/block.md
Labels: pr(documentation)
