Repository umijs/umi, pull requests merged in 2019-06, with the labels that each got.

#2512 fix: generate wrong dev url when history is hash
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/prepareUrls.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
Labels: pr(bug)

#2516 feat: bundle umi with father, export both esm and cjs
  .gitignore
  package.json
  packages/af-webpack/.fatherrc.js
  packages/af-webpack/package.json
  packages/babel-preset-umi/.fatherrc.js
  packages/eslint-config-umi/.fatherrc.js
  packages/umi-build-dev/.fatherrc.js
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/routes/stripJSONQuote.test.js
  packages/umi-core/.fatherrc.js
  packages/umi-mock/.fatherrc.js
  packages/umi-plugin-auto-externals/.fatherrc.js
  packages/umi-plugin-dll/.fatherrc.js
  packages/umi-plugin-dva/.fatherrc.js
  packages/umi-plugin-dva/package.json
  packages/umi-plugin-hd/.fatherrc.js
  packages/umi-plugin-locale/.fatherrc.js
  packages/umi-plugin-locale/package.json
  packages/umi-plugin-modern-mode/.fatherrc.js
  packages/umi-plugin-polyfills/README.md
  packages/umi-plugin-polyfills/package.json
  packages/umi-plugin-polyfills/src/ie10.js
  packages/umi-plugin-polyfills/src/ie11.js
  packages/umi-plugin-polyfills/src/ie9.js
  packages/umi-plugin-polyfills/src/index.js
  packages/umi-plugin-polyfills/yarn.lock
  packages/umi-plugin-react/.fatherrc.js
  packages/umi-plugin-routes/.fatherrc.js
  packages/umi-serve/.fatherrc.js
  packages/umi-test/.fatherrc.js
  packages/umi-types/.fatherrc.js
  packages/umi-types/src/.gitkeep
  packages/umi-utils/.fatherrc.js
  packages/umi/.fatherrc.js
  packages/umi/index.js
  packages/umi/package.json
  packages/umi/src/index.js
  packages/umi/src/utils.test.js
  yarn.lock
Labels: pr(enhancement)

#2515 feat: support --page for block add
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/index.test.js
Labels: pr(enhancement), type(block)

#2527 fix: revert uglify-webpack-plugin to 1.x
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/uglifyOptions.js
  packages/af-webpack/yarn.lock
  packages/umi-plugin-react/yarn.lock
Labels: pr(bug)

#2526 docs onBuildSuccessAsync
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: type(documentation)

#2531 chore: remove invalid code
  jest.config.js
Labels: pr(chore)

#2529 dep: webpack-bundle-analyzer -> umi-webpack-bundle-analyzer
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
Labels: pr(dependency)

#2536 feat: add env variable: ANALYZE_REPORT to generate bundle report file
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/test/build.test.js
Labels: pr(enhancement)

#2548 fix: open editor feature when click on error overlay
  packages/af-webpack/src/errorOverlayMiddleware.js
Labels: pr(bug)

#2551 fix(umi-plugin-locale): React undefined
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
Labels: pr(bug)

#2550 refactor: skip lock core-js plugin if possible
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
  packages/umi-build-dev/src/plugins/targets.js
Labels: pr(chore)

#2547 feat: support .graphql, .gql
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/test/fixtures/graphql/expected/index.js
  packages/af-webpack/test/fixtures/graphql/index.js
  packages/af-webpack/test/fixtures/graphql/test.gql
  packages/af-webpack/yarn.lock
Labels: pr(enhancement)

#2555 fix: umi block add 命令支持添加 window 环境下包的绝对路径
  packages/umi-build-dev/src/plugins/commands/block/download.js
Labels: pr(bug)

#2561 docs: add module process explaination
  docs/.vuepress/config.js
  docs/guide/module-processor.md
  docs/zh/guide/module-processor.md
Labels: pr(documentation)

#2565 doc: autoprefixer
  docs/config/README.md
  docs/zh/config/README.md
Labels: pr(documentation)

#2567 fix: import { Route } from 'umi';
  packages/umi/index.d.ts
  packages/umi/package.json
Labels: pr(bug)

#2570 fix(umi-types): add block entry to IConfig
  packages/umi-types/config.d.ts
Labels: pr(bug)

#2541 feat(block): select npm registry automatically
  .gitignore
  .prettierignore
  .prettierrc
  .travis.yml
  README.md
  README_zh-CN.md
  azure-pipelines.yml
  package.json
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
  packages/umi-build-dev/src/plugins/commands/ui/index-debug.html
  packages/umi-plugin-hd/README.md
  packages/umi-plugin-locale/README.md
  packages/umi-plugin-modern-mode/README.md
  packages/umi-plugin-routes/README.md
  packages/umi-serve/README.md
  packages/umi-types/README.md
Labels: pr(enhancement)

#2581 fix(umi-test): multiple react versions
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: pr(bug)

#2583 fix(umi): @tmp/umiExports module not found error when run tsc
  packages/umi/index.d.ts
Labels: pr(bug)

#2594 feat: support alias
  packages/umi-test/package.json
  packages/umi-test/src/index.js
Labels: pr(enhancement)

#2593 feat: set stats report file path to process.cwd()
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/test/build.test.js
Labels: pr(enhancement)

#2605 chore: update `umi-test` deps
  packages/umi-test/package.json
Labels: pr(dependency)

#2611 fix: don't tamper the original opts.extraBabelIncludes
  packages/af-webpack/src/getConfig/index.js
Labels: pr(bug)

#2554 feat(block): support convert ts to js
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/getBlockGenerator.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/tsTojs.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
Labels: pr(enhancement)

#2617 fix: watch 操作不需要传入 cwd
  packages/umi-build-dev/src/FilesGenerator.js
Labels: pr(bug)

#2618 fix(babel-preset-umi): don't transform object spread in some case
  packages/af-webpack/yarn.lock
  packages/babel-preset-umi/package.json
  packages/babel-preset-umi/src/index.js
  packages/babel-preset-umi/src/index.test.js
  packages/babel-preset-umi/yarn.lock
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-test/yarn.lock
Labels: pr(bug)

#2621 dep: upgrade eslint-config-react-app to 4 for hooks support
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/eslint-config-umi/package.json
  packages/eslint-config-umi/yarn.lock
  packages/umi-build-dev/yarn.lock
Labels: pr(dependency)

#2625 dep: upgrade preact, semver and clipboardy
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: pr(dependency)

#2627 fix: eslint's react version warning and babel-eslint dep lost
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/eslint-config-umi/src/index.js
  packages/umi-core/src/error.js
  scripts/startDevServers.js
Labels: pr(bug)

#2630 fix: use core-js and regenerator-runtime instead of @babel/polyfill
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/targets.js
  packages/umi-test/package.json
  packages/umi-test/src/shim.js
  packages/umi-test/yarn.lock
Labels: pr(bug)

#2632 fix(umi-plugin-auto-externals): chalk dep lost and change urllib to got
  packages/umi-plugin-auto-externals/package.json
  packages/umi-plugin-auto-externals/src/util/index.ts
  packages/umi-plugin-auto-externals/yarn.lock
Labels: pr(bug)

#2638 feat: support node 12
  .travis.yml
Labels: pr(enhancement)

#2637 doc: more doc about use block with js
  docs/zh/guide/block.md
Labels: pr(documentation)

#2639 doc: add locale documentation
  docs/api/README.md
  docs/zh/api/README.md
Labels: pr(documentation)

#2641 feat(block): support submodule
  docs/zh/guide/block.md
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
Labels: pr(enhancement)

#2643 chore: use father-build to bundle umi's packages
  package.json
  yarn.lock
Labels: pr(chore)

#2653 fix: dynamic compatibility
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
  packages/umi-plugin-react/src/plugins/antd.js
  packages/umi-plugin-react/src/plugins/dynamicImport.js
Labels: pr(bug)

#2659 fix: notlock types
  packages/umi/package.json
Labels: pr(bug)

#2655 doc: add docs for prerender
  docs/.vuepress/config.js
  docs/config/README.md
  docs/plugin/README.md
  docs/plugin/umi-plugin-prerender.md
  docs/zh/config/README.md
  docs/zh/plugin/umi-plugin-prerender.md
  packages/umi-plugin-prerender/README.md
  packages/umi-plugin-prerender/package.json
Labels: pr(documentation)

#2649 fix: prerender plugin add self polyfill
  packages/umi-plugin-prerender/src/index.ts
Labels: pr(bug)

#2660 fix: 修复 findRouter windows 路径问题
  packages/umi-build-dev/src/FilesGenerator.js
Labels: pr(bug)

#2662 fix: g_initialData in windows
  packages/umi-build-dev/src/FilesGenerator.js
Labels: pr(bug)

#2682 dep: upgrade webpack to 4.35
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/yarn.lock
Labels: pr(dependency)

#2670 fix(umi-build-dev): make moduleBeforeRendererPromises available for entry code
  packages/umi-build-dev/template/entry.js.tpl
Labels: pr(bug)

#2681 fix: ssr dev hot files should in memo
  packages/umi-build-dev/src/getWebpackConfig.js
Labels: pr(bug)

#2700 fix: remove unnecessary webpack-dev-middleware
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-build-dev/yarn.lock
Labels: pr(bug)

#2703 fix getLocale() return undefined
  packages/umi-plugin-locale/src/locale.js
Labels: pr(bug)

#2702 fix: findRoute.js with es6 syntax
  packages/umi-build-dev/.fatherrc.js
  packages/umi/test/build.e2e.ts
  packages/umi/test/fixtures/build/x-auto-external-unpkg/.umirc.js
  packages/umi/test/fixtures/build/x-auto-external-unpkg/package.json
  packages/umi/test/fixtures/build/x-auto-external-unpkg/pages/index.js
  packages/umi/test/fixtures/build/x-auto-external-unpkg/test.js
Labels: pr(bug)

#2680 chore: add PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
Labels: pr(chore)

#2677 doc: update router.md
  docs/guide/router.md
  docs/zh/guide/router.md
Labels: pr(documentation)

#2705 feat(af-webpack): remember user choosed port
  packages/af-webpack/src/dev.js
  packages/af-webpack/src/fork.js
Labels: pr(enhancement)

#2706 docs: more info about .env
  docs/guide/app-structure.md
  docs/zh/guide/app-structure.md
Labels: pr(documentation)

#2207 chore: support run ci for windows
  .prettierignore
  azure-pipelines.yml
  packages/af-webpack/test/build.test.js
  packages/af-webpack/test/fixtures/svgr/expected/index.js
  packages/af-webpack/test/fixtures/svgr/logo.svg
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/Service.test.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/getPlugins.test.js
  packages/umi-build-dev/src/html/HTMLGenerator.test.js
  packages/umi-build-dev/src/plugins/commands/block/insertComponent.js
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
  packages/umi-core/package.json
  packages/umi-core/src/getUserConfig.test.ts
  packages/umi-core/src/getUserConfig.ts
  packages/umi-mock/src/getMockData.js
  packages/umi-mock/src/getMockData.test.js
  packages/umi-mock/src/getPaths.js
  packages/umi-plugin-locale/test/index.test.js
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.js
  packages/umi-plugin-react/src/plugins/pwa/generateWebManifest.test.js
  packages/umi-utils/src/compatDirname.js
  packages/umi-utils/src/compatDirname.test.js
  packages/umi-utils/src/index.js
  packages/umi-utils/src/winEOL.js
  packages/umi-utils/src/winEOL.test.js
Labels: pr(chore)

#2708 fix: disable dll when use ssr
  packages/umi-plugin-dll/src/index.js
  packages/umi-types/index.d.ts
Labels: pr(bug)

#2540 umi block support ts
  packages/umi-build-dev/src/fixtures/block/antdprots/config/config.ts
  packages/umi-build-dev/src/fixtures/block/antdprots/config/plugin.config.ts
  packages/umi-build-dev/src/fixtures/block/antdprots/config/router.config.ts
  packages/umi-build-dev/src/fixtures/block/antdprots/package.json
  packages/umi-build-dev/src/fixtures/block/antdprots/pages/index.tsx
  packages/umi-build-dev/src/utils/writeNewRoute.js
  packages/umi-build-dev/src/utils/writeNewRoute.test.js
Labels: pr(bug), type(block)

#2245 fix(block): allow an IP to be the host of git (#2191)
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/download.test.js
Labels: pr(enhancement), type(block)

#2484 feat(umi-plugin-locale): support locale file in commonjs module format
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
Labels: pkg(umi-plugin-locale), pr(enhancement)

#2713 fix: 去掉 临时方案 locale @types
  packages/umi-plugin-locale/index.d.ts
Labels: pr(bug)

#2718 fix: don't resolve versions from user's package.json for react-router, react-router-dom and react-router-config
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
Labels: pr(bug)

#2687 feat(block): support local umi list
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/plugins/commands/block/index.js
  packages/umi-build-dev/src/plugins/commands/block/util.js
  packages/umi-build-dev/yarn.lock
  packages/umi/package.json
  packages/umi/src/cli.js
Labels: pr(enhancement), type(block)

#2717 fix: base should add to pathname rather than hash when history mode i…
  packages/af-webpack/src/prepareUrls.js
Labels: pr(bug)

#2724 feat: support config dva dir from env variable
  packages/umi-plugin-dva/src/index.js
Labels: pr(enhancement)
