Repository umijs/umi, pull requests merged in 2019-02, with the labels that each got.

#1943 doc: add create plugin doc with create-umi
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
Labels: documentation

#1952 feat: use a complex NotFound css name for potential conflict problems when user disabled css modules
  packages/umi-build-dev/src/plugins/404/NotFound.js
  packages/umi-build-dev/src/plugins/404/NotFound.less
Labels: enhancement

#1915 export interface RouteData
  packages/umi/router.d.ts
Labels: enhancement

#1953 feat: support use @ in mock files
  packages/af-webpack/src/registerBabel.js
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
  packages/umi-build-dev/src/registerBabel.js
  packages/umi-build-dev/yarn.lock
  packages/umi/test/fixtures/e2e/normal/mock/users.js
  packages/umi/test/fixtures/e2e/normal/src/app.js
  packages/umi/test/fixtures/e2e/normal/src/assets/antd.png
  packages/umi/test/fixtures/e2e/normal/src/assets/dva.jpg
  packages/umi/test/fixtures/e2e/normal/src/assets/roadhog.jpg
  packages/umi/test/fixtures/e2e/normal/src/assets/yuque.png
  packages/umi/test/fixtures/e2e/normal/src/cc.js
  packages/umi/test/fixtures/e2e/normal/src/global.css
  packages/umi/test/fixtures/e2e/normal/src/global.js
  packages/umi/test/fixtures/e2e/normal/src/layouts/index.js
  packages/umi/test/fixtures/e2e/normal/src/pages/404.js
  packages/umi/test/fixtures/e2e/normal/src/pages/index.css
  packages/umi/test/fixtures/e2e/normal/src/pages/index.js
  packages/umi/test/fixtures/e2e/normal/src/pages/list.js
Labels: enhancement

#1954 doc: fix typo
  docs/zh/guide/block.md
Labels: documentation

#1956 feat: support config mock.exclude
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
  packages/umi-build-dev/src/plugins/mock/index.js
Labels: enhancement

#1958 chore: use now@2
  .gitignore
  website/.gitignore
  website/now.json
  website/package.json
  website/server.js
Labels: chore

#1964 doc: translate
  docs/config/README.md
  docs/guide/html-template.md
Labels: documentation

#1969 feat: extract umi-mock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/mock.js
  packages/umi-build-dev/src/plugins/mock/createMockMiddleware.js
  packages/umi-mock/package.json
  packages/umi-mock/src/createMiddleware.js
  packages/umi-mock/src/fixtures/mock-files/a.js
  packages/umi-mock/src/fixtures/mock-files/a_2.js
  packages/umi-mock/src/fixtures/mock-files/b.js
  packages/umi-mock/src/fixtures/mock-files/string.js
  packages/umi-mock/src/fixtures/mock-files/with-keys.js
  packages/umi-mock/src/fixtures/normal/mock/_c.js
  packages/umi-mock/src/fixtures/normal/mock/a.js
  packages/umi-mock/src/fixtures/normal/mock/b.js
  packages/umi-mock/src/fixtures/normal/pages/a/_mock.js
  packages/umi-mock/src/fixtures/normal/pages/b/_mock.js
  packages/umi-mock/src/fixtures/umirc-mock-file/.umirc.mock.js
  packages/umi-mock/src/fixtures/umirc-mock-file/mock/a.js
  packages/umi-mock/src/getMockData.js
  packages/umi-mock/src/getMockData.test.js
  packages/umi-mock/src/getPaths.js
  packages/umi-mock/src/index.js
  packages/umi-mock/src/matchMock.js
  packages/umi-mock/yarn.lock
Labels: enhancement

#1967 feat: support speed measure webpack plugin
  docs/guide/env-variables.md
  docs/zh/guide/env-variables.md
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/umi-build-dev/src/plugins/afwebpack-config.js
Labels: enhancement

#1973 fix: manifest fileName
  docs/config/README.md
Labels: documentation

#1972 fix: manifest fileName
  docs/zh/config/README.md
Labels: documentation

#1971 feat: add umi-serve
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/UserConfig.js
  packages/umi-build-dev/src/UserConfig.test.js
  packages/umi-build-dev/src/constants.js
  packages/umi-build-dev/src/getPaths.js
  packages/umi-build-dev/src/getPlugins.js
  packages/umi-build-dev/src/registerBabel.js
  packages/umi-core/package.json
  packages/umi-core/src/fixtures/getUserConfig/config-directory/config/config.js
  packages/umi-core/src/fixtures/getUserConfig/conflicts/.umirc.js
  packages/umi-core/src/fixtures/getUserConfig/conflicts/config/config.js
  packages/umi-core/src/fixtures/getUserConfig/umirc/.umirc.js
  packages/umi-core/src/getPaths.js
  packages/umi-core/src/getUserConfig.js
  packages/umi-core/src/getUserConfig.test.js
  packages/umi-core/yarn.lock
  packages/umi-serve/.local
  packages/umi-serve/bin/umi-serve.js
  packages/umi-serve/package.json
  packages/umi-serve/yarn.lock
  packages/umi/src/cli.js
Labels: enhancement

#1979 feat: upgrade deps, including webpack@4.29, react@16.8
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/registerBabel.js
  packages/umi-build-dev/yarn.lock
  packages/umi-serve/package.json
  packages/umi-serve/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
  packages/umi/package.json
  packages/umi/yarn.lock
Labels: enhancement

#1990 feat: improve mock error print
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/src/plugins/mock.js
  packages/umi-mock/src/createMiddleware.js
  packages/umi-mock/src/getMockData.js
  packages/umi-mock/yarn.lock
Labels: enhancement

#1989 fix: generate smp file to process.cwd
  packages/af-webpack/src/getConfig/index.js
Labels: bug

#1987 fix: revert webpack to 4.28 since npm breaks webpack@4.29
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
  packages/umi-plugin-react/package.json
  packages/umi-plugin-react/yarn.lock
Labels: bug

#1994 fix: mock watch only include _mock.js in pages
  packages/umi-mock/src/createMiddleware.js
Labels: bug

#1995 feat: support config files and mock files in TypeScript
  packages/af-webpack/package.json
  packages/af-webpack/src/registerBabel.js
  packages/af-webpack/yarn.lock
  packages/umi-core/src/getUserConfig.ts
  packages/umi-mock/src/createMiddleware.js
  packages/umi-mock/src/fixtures/ts/mock/a.ts
  packages/umi-mock/src/getMockData.js
  packages/umi-mock/src/getMockData.test.js
  packages/umi-mock/src/getPaths.js
  packages/umi-serve/bin/umi-serve.js
  packages/umi-serve/package.json
  packages/umi-serve/yarn.lock
Labels: enhancement

#1997 feat(umi-test): upgrade ts-jest to 24
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: enhancement

#1996 fix: 解决 windows 下 glob 用反斜杠无法触发watch事件的问题
  packages/umi-mock/src/createMiddleware.js
Labels: bug

#1999 feat: upgrade enzyme to 3.9
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: enhancement

#2001 fix: 修复 CheerioSelector 类型丢失 & 为 IRoute 添加 `redirect` 类型路由
  packages/umi-types/config.d.ts
  packages/umi-types/index.d.ts
Labels: bug

#2003 feat(umi-types): add api.register and fix IPkg
  packages/umi-types/index.d.ts
Labels: enhancement

#2008 feat(af-webpack): upgrade copy-webpack-plugin to 5
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: enhancement

#2009 feat: upgrade webpack-dev-server to 3.2
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: dependency

#2013 feat: upgrade react to 16.8.3
  packages/umi-build-dev/package.json
  packages/umi-build-dev/yarn.lock
  packages/umi-test/package.json
  packages/umi-test/yarn.lock
Labels: pr: dependency

#2015 fix: umi test don't work if have console.log
  packages/umi-build-dev/src/plugins/commands/test.js
Labels: bug

#2022 fix: use a simple progress plugin for windows
  packages/af-webpack/package.json
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/yarn.lock
Labels: pr: bug

#2023 fix: update registerBabel targets to node 8
  packages/umi-build-dev/src/registerBabel.js
  packages/umi-serve/bin/umi-serve.js
Labels: pr: bug

#2036 feat: allow the interface to be extended from IRoute
  packages/umi-types/config.d.ts
Labels: pr: enhancement
