Repository umijs/umi, pull requests merged in 2019-12, with the labels that each got.

#3727 fix: bigfish ui locale error when add template
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
Labels: pr(bug)

#3730 Remove extra parentheses
  docs/zh/api/README.md
Labels: pr(documentation)

#3729 dep: upgrade eslint-config-react-app
  packages/eslint-config-umi/package.json
Labels: pr(dependency)

#3743 fix: 修复绑定onpopstate与三方库已有方法冲突
  packages/umi/src/renderRoutes.js
Labels: type(bug)

#3751 feat: support layout getInitialProps & dynamicImport & greatly enhance ssr
  netlify.toml
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/src/findRoute.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-build-dev/template/router.js.tpl
  packages/umi-ui/package.json
  packages/umi/package.json
  packages/umi/src/renderRoutes.js
Labels: pr(bug), pr(enhancement), type(ssr)

#3755 fix: umi-ui-tasks spawn error in windows
  packages/umi-ui-tasks/package.json
  packages/umi-ui-tasks/src/server/util/index.ts
Labels: pr(bug)

#3756 fix: ssr location object
  packages/umi-build-dev/package.json
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-ui/package.json
  packages/umi/package.json
Labels: pr(chore)

#3759 fix: $ should not appear in prod file name
  packages/umi-build-dev/src/routes/routesToJSON.js
  packages/umi-build-dev/src/utils/getChunkMap.test.js
  packages/umi-build-dev/src/utils/getChunkMap.ts
  packages/umi/test/fixtures/build/umi-plugin-react/pages/$user.js
  packages/umi/test/fixtures/build/umi-plugin-react/test.js
Labels: pr(bug)

#3767 refactor: umi-ui-tasks Terminal use api & blocks check
  .gitignore
  packages/umi-build-dev/src/plugins/commands/block/ui/client/BlocksViewer.module.less
  packages/umi-build-dev/src/plugins/commands/block/ui/client/LogPanel/index.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
  packages/umi-build-dev/src/plugins/commands/block/util.ts
  packages/umi-ui-tasks/package.json
  packages/umi-ui-tasks/src/locales/zh-CN.js
  packages/umi-ui-tasks/src/types/global.d.ts
  packages/umi-ui-tasks/src/ui.tsx
  packages/umi-ui-tasks/src/ui/components/Build/index.tsx
  packages/umi-ui-tasks/src/ui/components/Dev/index.tsx
  packages/umi-ui-tasks/src/ui/components/Install/index.tsx
  packages/umi-ui-tasks/src/ui/components/Lint/index.tsx
  packages/umi-ui-tasks/src/ui/components/Terminal/index.module.less
  packages/umi-ui-tasks/src/ui/components/Terminal/index.tsx
  packages/umi-ui-tasks/src/ui/components/Test/index.tsx
  packages/umi-ui-tasks/src/ui/components/index.ts
  packages/umi-ui-tasks/src/ui/hooks/index.ts
  packages/umi-ui-tasks/src/ui/hooks/terminal.ts
  packages/umi-ui-tasks/src/ui/model/index.ts
  packages/umi-ui-tasks/src/ui/util/terminal.ts
  packages/umi-ui-tasks/yarn.lock
  packages/umi-ui/client/.env
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/package.json
  packages/umi-ui/client/src/components/Terminal/index.module.less
  packages/umi-ui/client/src/components/Terminal/index.tsx
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
  packages/umi-ui/client/src/global.less
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/layouts/FooterToolbar.tsx
  packages/umi-ui/client/src/pages/document.ejs
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/client/yarn.lock
  packages/umi-ui/src/UmiUI.ts
  packages/umi-ui/yarn.lock
Labels: pr(chore)

#3780 fix: GUmiUIFlag Component show in open Umi UI
  packages/umi-build-dev/src/plugins/commands/block/sdk/flagBabelPlugin/GUmiUIFlag.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/client/BlockList/getInsertPosition.tsx
  packages/umi-build-dev/src/plugins/commands/block/ui/index.ts
Labels: pkg(umi-ui), pr(bug)

#3776 fix: react-router-dom and react types version
  package.json
  packages/umi-ui-tasks/src/package.json
  packages/umi/package.json
Labels: pr(bug), type(TypeScript)

#3781 fix: umi ui blocks page target path exist
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkBindingInFile.ts
  packages/umi-ui/src/fixtures/Config/illegal.json
Labels: pkg(umi-ui), pr(bug)

#3798 fix: ui block locale add check
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/index.test.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/socketHandlers/org.umi.block.checkIfCanAdd.ts
Labels: pkg(umi-plugin-ui), pr(bug)

#3791 fix: .env and .env.local priority
  packages/umi/src/buildDevOpts.js
  packages/umi/src/buildDevOpts.test.js
  packages/umi/src/fixtures/buildDevOpts/.env
  packages/umi/src/fixtures/buildDevOpts/.env.local
Labels: pr(bug)

#3799 feat: extend ui sider footer
  package.json
  packages/umi-types/ui.d.ts
  packages/umi-ui/client/.umirc.ts
  packages/umi-ui/client/src/PluginAPI.ts
  packages/umi-ui/client/src/app.ts
  packages/umi-ui/client/src/components/ErrorBoundary/index.tsx
  packages/umi-ui/client/src/components/Terminal/index.tsx
  packages/umi-ui/client/src/components/TwoColumnPanel/index.tsx
  packages/umi-ui/client/src/layouts/BetaPlugin.tsx
  packages/umi-ui/client/src/layouts/Dashboard.less
  packages/umi-ui/client/src/layouts/Dashboard.tsx
  packages/umi-ui/client/src/layouts/Footer.tsx
  packages/umi-ui/client/src/pages/loading/index.tsx
  packages/umi-ui/client/src/pages/project/components/list/index.tsx
  packages/umi-ui/client/src/pages/project/components/progress/index.tsx
  packages/umi-ui/client/src/utils/index.tsx
Labels: Feature Request, pkg(umi-ui)

#3802 fix: umi ui block download spawn in windows
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/commands/block/download.js
Labels: pr(bug)

#3813 feat(umi-ui): don't show welcome card in dashboard
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.tsx
Labels: pr(enhancement)

#3812 chore(umi-ui): exclude fixtures directory to npm package
  .gitignore
  packages/umi-plugin-ui/package.json
Labels: pr(chore)

#3824 fix: umi-ui header
  packages/umi-ui/client/src/layouts/Dashboard.less
  packages/umi-ui/client/src/layouts/Dashboard.tsx
Labels: pr(bug)

#3826 docs: umi ui docs
  docs/guide/umi-ui.md
  docs/zh/guide/umi-ui.md
Labels: pr(documentation)

#3837 fix: api.getRouteComponents bug
  packages/af-webpack/yarn.lock
  packages/umi-build-dev/src/Service.js
  packages/umi-build-dev/src/Service.test.js
  packages/umi-build-dev/src/fixtures/Service/get-routes-components/.umirc.js
  packages/umi-build-dev/src/fixtures/Service/get-routes-components/src/pages/index.js
  packages/umi-build-dev/src/fixtures/Service/get-routes-components/src/pages/news.js
  packages/umi-build-dev/src/plugins/commands/block/ui/index.ts
  packages/umi-build-dev/yarn.lock
  packages/umi-plugin-ui/src/plugins/dashboard/ui/index.module.less
  packages/umi-types/index.d.ts
  packages/umi/yarn.lock
  yarn.lock
Labels: pr(bug)

#3843 docs: Update config URL in the router.md
  docs/guide/router.md
  docs/zh/guide/router.md
Labels: pr(documentation)

#3845 docs: locale doc
  docs/api/README.md
  docs/zh/api/README.md
Labels: pr(documentation)

#3848 fix: Umi UI header theme style
  packages/umi-ui-theme/dark.less
  packages/umi-ui-theme/test/index.test.ts
Labels: pr(bug)

#3851 feat: locale plugin support .json files
  packages/umi-plugin-locale/README.md
  packages/umi-plugin-locale/examples/multiple-ext/config/config.js
  packages/umi-plugin-locale/examples/multiple-ext/package.json
  packages/umi-plugin-locale/examples/multiple-ext/src/app.js
  packages/umi-plugin-locale/examples/multiple-ext/src/locale/en-US.js
  packages/umi-plugin-locale/examples/multiple-ext/src/locale/sk.json
  packages/umi-plugin-locale/examples/multiple-ext/src/locale/zh-CN.ts
  packages/umi-plugin-locale/examples/multiple-ext/src/page/index.js
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/index.js
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/en-US.js
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/en-US/t.js
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/sk.json
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/test.js
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/locale/zh-CN.ts
  packages/umi-plugin-locale/examples/multiple-ext/src/page/temp/model.js
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/test/index.test.js
Labels: pkg(umi-plugin-locale), pr(enhancement)
