Repository umijs/umi, pull requests merged in 2019-03, with the labels that each got.

#2029 feat: use contenthash instead of chunkhash for better long-term caching
  packages/af-webpack/src/getConfig/prod.js
Labels: enhancement

#2057 chore: convert indexOf to use includes when checking for a missing index
  packages/af-webpack/src/formatWebpackMessages.js
  packages/af-webpack/src/getConfig/FilterCSSConflictingWarning.js
  packages/af-webpack/src/getConfig/index.js
  packages/af-webpack/test/build.test.js
  scripts/publish.js
Labels: pr: chore

#2059 feat(umi-library): improve logs, docs
  packages/umi-library/README.md
  packages/umi-library/package.json
  packages/umi-library/src/babel.ts
  packages/umi-library/src/build.ts
  packages/umi-library/src/fixtures/build/target-node/.umirc.library.js
  packages/umi-library/src/fixtures/build/target-node/expected/index.esm.js
  packages/umi-library/src/fixtures/build/target-node/src/index.js
  packages/umi-library/src/getRollupConfig.ts
  packages/umi-library/src/index.ts
  packages/umi-library/src/rollup.ts
  packages/umi-library/src/schema.test.ts
  packages/umi-library/src/schema.ts
  packages/umi-library/src/types.d.ts
Labels: enhancement

#2062 feat: add onStartAsync hook for build and dev
  packages/umi-build-dev/CHANGELOG.md
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-build-dev/src/plugins/commands/dev/index.js
  packages/umi-types/index.d.ts
Labels: pr: enhancement

#2064 fix(umi-library): bin is not included
  packages/umi-library/package.json
Labels: pr: bug

#2067 feat: add doc deploy
  packages/umi-library/README.md
  packages/umi-library/package.json
  packages/umi-library/src/doc.ts
Labels: pr: enhancement

#2077 fix: lost type definition in config of umi-library
  packages/umi-library/package.json
  packages/umi-library/src/types.d.ts
  packages/umi-library/yarn.lock
Labels: pr: bug

#2081 doc: translate runtime config
  docs/guide/runtime-config.md
Labels: pr: documentation

#2084 feat(umi-library): more babel features such as decorator
  packages/umi-library/package.json
  packages/umi-library/src/doczrc.ts
  packages/umi-library/src/fixtures/build/babel-syntax/.umirc.library.js
  packages/umi-library/src/fixtures/build/babel-syntax/expected/index.esm.js
  packages/umi-library/src/fixtures/build/babel-syntax/src/a.js
  packages/umi-library/src/fixtures/build/babel-syntax/src/b.js
  packages/umi-library/src/fixtures/build/babel-syntax/src/index.js
  packages/umi-library/src/fixtures/doc/normal/button/index.js
  packages/umi-library/src/getBabelConfig.ts
  packages/umi-library/yarn.lock
Labels: pr: enhancement

#2085 fix(umi-library): extraBabelPresets and extraBabelPlugins don't work
  packages/umi-library/src/doczrc.ts
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/.umirc.library.js
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/README.mdx
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/b.less
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/c.module.less
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.css
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.js
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.mdx
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.module.css
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/p1.js
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/p2.js
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/package.json
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/preset.js
Labels: pr: bug

#2086 fix(umi-library): can't import directory
  packages/umi-library/src/fixtures/build/babel-syntax/package.json
  packages/umi-library/src/fixtures/build/rollup-import-directory/.umirc.library.js
  packages/umi-library/src/fixtures/build/rollup-import-directory/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-import-directory/src/foo/index.js
  packages/umi-library/src/fixtures/build/rollup-import-directory/src/index.js
  packages/umi-library/src/getRollupConfig.ts
Labels: pr: bug

#2088 fix(umi-library): babel mode should ignore non js files
  packages/umi-library/src/babel.ts
  packages/umi-library/src/fixtures/build/babel-normal/expected/es/bar.md
  packages/umi-library/src/fixtures/build/babel-normal/expected/lib/bar.md
  packages/umi-library/src/fixtures/build/babel-normal/src/bar.md
Labels: pr: bug

#2092 dep(af-webpack): upgrade copy-webpack-plugin to 5.0.1
  packages/af-webpack/package.json
  packages/af-webpack/yarn.lock
Labels: pr: dependency

#2075 feat(umi-library): auto detect typescript in docz
  packages/umi-library/src/doczrc.ts
Labels: pr: enhancement

#2100 feat(umi-types): add block api definition
  packages/umi-types/index.d.ts
Labels: pr: enhancement

#2102 fix: block IBlockDependencies define
  packages/umi-types/index.d.ts
Labels: pr: bug

#2105 feat(umi-test): use babel for typescript transform, enzyme multiple instance problem, and etc
  jest.config.js
  packages/umi-test/bin/umi-test.js
  packages/umi-test/package.json
  packages/umi-test/src/index.js
  packages/umi-test/src/transformers/jsTransformer.js
  packages/umi-test/src/transformers/tsTransformer.js
  packages/umi-test/yarn.lock
Labels: pr: enhancement

#2096 fix(umi-library): support array like config in config.history
  docs/config/README.md
  docs/zh/config/README.md
  packages/umi-build-dev/src/plugins/history.js
Labels: pr: enhancement

#2106 feat(umi-library): improve umi-library, internal refact, error handler, and etc
  jasmine.js
  jest.config.js
  package.json
  packages/umi-library/README.md
  packages/umi-library/bin/umi-library.js
  packages/umi-library/package.json
  packages/umi-library/src/doc.test.ts
  packages/umi-library/src/doc.ts
  packages/umi-library/src/doczrc.ts
  packages/umi-library/src/fixtures/e2e/normal/README.mdx
  packages/umi-library/src/fixtures/e2e/normal/button/b.less
  packages/umi-library/src/fixtures/e2e/normal/button/c.module.less
  packages/umi-library/src/fixtures/e2e/normal/button/index.css
  packages/umi-library/src/fixtures/e2e/normal/button/index.js
  packages/umi-library/src/fixtures/e2e/normal/button/index.mdx
  packages/umi-library/src/fixtures/e2e/normal/button/index.module.css
  packages/umi-library/src/fixtures/e2e/normal/expected/index.esm.js
  packages/umi-library/src/fixtures/e2e/normal/package.json
  packages/umi-library/src/fixtures/e2e/normal/src/index.js
  packages/umi-library/src/index.ts
  packages/umi-library/src/umi-library.e2e.ts
  yarn.lock
Labels: pr: enhancement

#2107 feat: add plugin hook `onBuildSuccessAsync`
  docs/plugin/develop.md
  docs/zh/plugin/develop.md
  packages/umi-build-dev/src/PluginAPI.js
  packages/umi-build-dev/src/plugins/commands/build/index.js
  packages/umi-types/index.d.ts
Labels: pr: enhancement

#2109 fix(umi-test): use project's enzyme dependencies if found
  packages/umi-test/src/transformers/jsTransformer.js
  packages/umi-test/yarn.lock
  packages/umi-utils/src/compatDirname.js
Labels: pr: bug

#2112 feat(umi-library): use package name as umd name by default
  packages/umi-library/README.md
  packages/umi-library/src/fixtures/build/rollup-umd-auto-name/.umirc.library.js
  packages/umi-library/src/fixtures/build/rollup-umd-auto-name/expected/index.umd.js
  packages/umi-library/src/fixtures/build/rollup-umd-auto-name/package.json
  packages/umi-library/src/fixtures/build/rollup-umd-auto-name/src/index.js
  packages/umi-library/src/getRollupConfig.ts
Labels: pr: enhancement

#2111 feat: add umi router types
  packages/umi/index.d.ts
  packages/umi/routerTypes.d.ts
Labels: TypeScript, pr: enhancement

#2115 types: chain webpack
  packages/umi-types/index.d.ts
  packages/umi-types/package.json
  packages/umi-types/yarn.lock
Labels: TypeScript, pr: enhancement

#2116 docs: enhance readability for umi-library
  packages/umi-library/README.md
Labels: pr: documentation

#2124 fix(umi-library): css modules config don't work with doc
  packages/umi-library/src/doczrc.ts
  packages/umi-library/src/fixtures/build/rollup-typescript/.umirc.library.ts
  packages/umi-library/src/fixtures/build/rollup-typescript/src/index.ts
  packages/umi-library/src/fixtures/build/rollup-typescript/typings.d.ts
  packages/umi-library/src/fixtures/doc/config-theme/.umirc.library.js
  packages/umi-library/src/fixtures/doc/css-modules/.umirc.library.js
  packages/umi-library/src/fixtures/doc/css-modules/button/index.css
  packages/umi-library/src/fixtures/doc/css-modules/button/index.js
  packages/umi-library/src/fixtures/doc/css-modules/button/index.mdx
  packages/umi-library/src/fixtures/doc/css-modules/package.json
Labels: pr: bug

#2130 fix(umi-library): require node_modules in sub directory problem
  packages/umi-library/README.md
  packages/umi-library/src/build.ts
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/.umirc.library.js
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/expected/index.umd.js
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/package.json
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/node_modules/timing2/lib/index.js
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/node_modules/timing2/package.json
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/package.json
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/src/index.js
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/packages/fooo/yarn.lock
  packages/umi-library/src/fixtures/build/require-node_modules-in-sub-directory/src/index.js
  packages/umi-library/src/fixtures/build/rollup-commonjs-deps-named-exports/expected/index.umd.js
  packages/umi-library/src/fixtures/build/rollup-commonjs-deps/expected/index.umd.js
  packages/umi-library/src/fixtures/build/rollup-css-autoprefixer/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-css-modules/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-css/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-less-modules/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-less-node-modules/expected/index.esm.js
  packages/umi-library/src/fixtures/build/rollup-less/expected/index.esm.js
  packages/umi-library/src/fixtures/e2e/normal/expected/index.esm.js
  packages/umi-library/src/getRollupConfig.ts
Labels: pr: bug

#2119 feat(umi-library): docz config shall be read from .umi.library.* without intermediate .umi.library.json generated
  packages/umi-library/src/doc.ts
  packages/umi-library/src/doczrc.ts
  packages/umi-library/yarn.lock
Labels: pr: enhancement

#2132 fix(umi-library): package size too large
  packages/umi-library/.npmignore
  packages/umi-library/package.json
Labels: pr: bug

#2133 doc: fix
  docs/plugin/umi-plugin-react.md
  docs/zh/plugin/umi-plugin-react.md
Labels: pr: documentation

#2128 doc: update runtime-config.md
  docs/zh/guide/runtime-config.md
Labels: pr: documentation

#2136 fix: lock core-js's version
  packages/umi-build-dev/package.json
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
  packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
  packages/umi-build-dev/yarn.lock
Labels: pr: bug

#2138 fix: typo
  packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
Labels: pr: bug

#2139 fix: core js version lock
  packages/umi-build-dev/src/plugins/afwebpack-config/index.js
  packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
Labels: pr: bug

#2141 fix(umi-library): docz could accept extra userConfig
  package.json
  packages/umi-library/src/doc.e2e.ts
  packages/umi-library/src/doc.ts
  packages/umi-library/src/doczrc.ts
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/README.mdx
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/b.less
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/c.module.less
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.css
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.js
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.mdx
  packages/umi-library/src/fixtures/doc/babel-extra-babel-presets-and-plugins/button/index.module.css
  packages/umi-library/src/fixtures/doc/normal/.umirc.library.js
  yarn.lock
Labels: pr: bug

#2144 dep: upgrade rollup related deps
  packages/umi-library/package.json
  packages/umi-library/src/fixtures/build/babel-syntax/expected/index.esm.js
  packages/umi-library/yarn.lock
Labels: pr: dependency

#2146 fix: e2e test with umi build
  package.json
  packages/umi/test/build.e2e.ts
  packages/umi/test/build.test.js
  packages/umi/test/fixtures/build/export-static-htmlSuffix/.umirc.js
  packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/index.html
  packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/list.html
  packages/umi/test/fixtures/build/export-static-htmlSuffix/expected/umi.js
  packages/umi/test/fixtures/build/export-static-htmlSuffix/test.js
  packages/umi/test/fixtures/build/export-static/.umirc.js
  packages/umi/test/fixtures/build/export-static/expected/index.html
  packages/umi/test/fixtures/build/export-static/expected/list/index.html
  packages/umi/test/fixtures/build/export-static/expected/umi.js
  packages/umi/test/fixtures/build/export-static/test.js
  packages/umi/test/fixtures/build/runtime-public-path/.umirc.js
  packages/umi/test/fixtures/build/runtime-public-path/pages/index.js
  packages/umi/test/fixtures/build/runtime-public-path/test.js
  packages/umi/test/fixtures/build/runtimePublicPath/.umirc.js
  packages/umi/test/fixtures/build/runtimePublicPath/expected/index.html
  packages/umi/test/fixtures/build/runtimePublicPath/expected/umi.js
  packages/umi/test/fixtures/build/simple/.umirc.js
  packages/umi/test/fixtures/build/simple/expected/index.html
  packages/umi/test/fixtures/build/simple/expected/umi.js
  packages/umi/test/fixtures/build/simple/pages/index.js
  packages/umi/test/fixtures/build/simple/test.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/.umirc.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/index.html
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/expected/umi.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/package.json
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/pages/index.js
  packages/umi/test/fixtures/build/tree-shaking-with-cjs/test.js
  yarn.lock
Labels: pr: bug

#2162 docs: Test and Inspect
  docs/guide/getting-started.md
Labels: pr: documentation

#2171 docs: [translate] Test and Inspect
  docs/zh/guide/getting-started.md
Labels: pr: documentation

#2172 fix: core-js's verson lock don't work in windows
  packages/umi-build-dev/src/plugins/afwebpack-config/lockCoreJSVersionPlugin.js
Labels: pr: bug

#2165 Update examples.md
  docs/guide/examples.md
Labels: pr: documentation

#2179 fix(umi-library): peerDependencies warning
  packages/umi-library/package.json
  packages/umi-library/yarn.lock
Labels: pr: bug

#2180 feat: improve umi-library
  packages/umi-library/bin/umi-library.js
  packages/umi-library/src/build.ts
Labels: pr: enhancement

#2181 feat(umi-test): support --transform-include option
  packages/umi-test/src/index.js
  packages/umi-test/src/transformers/jsTransformer.js
Labels: pr: enhancement

#2182 fix(umi-library): bundle opts validate typo
  packages/umi-library/src/build.ts
Labels: pr: bug

#2183 dep: upgrade eslint-config-react-app
  packages/eslint-config-umi/package.json
Labels: pr: dependency

#2184 feat(umi-library): add typing definition for umi-library
  packages/umi-library/index.d.ts
  packages/umi-library/package.json
Labels: pr: enhancement

#2187 feat(umi-library): ignore mdx files with babel mode
  packages/umi-library/README.md
  packages/umi-library/src/babel.ts
  packages/umi-library/src/fixtures/build/babel-normal/src/bar.mdx
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.e2e.ts
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.spec.ts
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.test.js
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.test.jsx
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.test.ts
  packages/umi-library/src/fixtures/build/babel-normal/src/foo.test.tsx
Labels: pr: enhancement

#2192 fix(umi-library): enable source-map for doc in dev mode
  packages/umi-library/src/doczrc.ts
Labels: pr: bug

#2193 fix: route could be sensitive
  packages/umi/src/renderRoutes.js
  packages/umi/test/fixtures/build/route-sensitive/.umirc.js
  packages/umi/test/fixtures/build/route-sensitive/pages/404.js
  packages/umi/test/fixtures/build/route-sensitive/pages/login.js
  packages/umi/test/fixtures/build/route-sensitive/test.js
Labels: pr: bug

#2194 fix: type definition of RouterTypes
  packages/umi/routerTypes.d.ts
Labels: pr: bug
