Repository umijs/umi, pull requests merged in 2020-03, with the labels that each got.

#4057 fix: mock with query
  packages/preset-built-in/src/plugins/commands/dev/mock/fixtures/mock-files/mock/with-query.js
  packages/preset-built-in/src/plugins/commands/dev/mock/utils.test.ts
  packages/preset-built-in/src/plugins/commands/dev/mock/utils.ts
Labels: pr(bug)

#4118 tweak: bundler exclude antd icons
  packages/bundler-webpack/src/getConfig/getConfig.ts
Labels: pr(enhancement)

#4135 fix: 2.x ci
  azure-pipelines.yml
  circle.yml
  packages/umi/yarn.lock
  yarn.lock
Labels: pr(chore)

#4151 fix: history runtime base
  packages/umi-build-dev/src/plugins/history.js
Labels: 2.x, pr(bug)

#4175 Automatically switch to the branch of umi@3
  packages/umi-build-dev/src/plugins/commands/block/download.js
  packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_clone.ts
  packages/umi-build-dev/src/plugins/commands/block/ui/server/core/tasks/git_update.ts
  packages/umi-build-dev/src/plugins/commands/block/util.ts
Labels: pr(bug)

#4184 fix: history basename
  packages/umi-build-dev/src/plugins/history.js
Labels: pr(bug)

#4191 feat: can import only-required-for-you polyfills by core-js
  docs/config/README.md
  docs/config/README.zh-CN.md
  packages/preset-built-in/src/plugins/generateFiles/core/polyfill.tpl
  packages/preset-built-in/src/plugins/generateFiles/core/polyfill.ts
  packages/types/index.d.ts
Labels: pr(enhancement)

#4236 fix: windows server undefined
  packages/server/src/Server/Server.ts
Labels: pr(bug)

#4240 fix: server https env
  packages/server/src/Server/Server.ts
Labels: pr(bug)

#4247 feat: umi config list command
  packages/preset-built-in/src/index.ts
  packages/preset-built-in/src/plugins/commands/config/config.ts
Labels: pr(enhancement)
