Repository umijs/umi, pull requests merged in 2020-04, with the labels that each got.

#4343 fix: prevent getInitialProps refire on hash change
  packages/umi/src/renderRoutes.js
  packages/umi/yarn.lock
  yarn.lock
Labels: type(bug)

#4362 fix(ssr): clone extraProps in SSR HOC
  packages/umi/src/renderRoutes.js
Labels: pr(bug)

#4386 Revert "fix: ssr initialValue"
  packages/umi-build-dev/src/FilesGenerator.js
  packages/umi-build-dev/template/entry.js.tpl
  packages/umi-plugin-dva/template/dva.js.tpl
  packages/umi/yarn.lock
  yarn.lock
Labels: pr(bug)

#4454 fix: is React Component
  packages/ast/src/isReactComponent/isReactComponent.test.ts
  packages/ast/src/isReactComponent/isReactComponent.ts
Labels: pr(bug)

#4455 chore: ts checker options
  packages/preset-built-in/src/plugins/features/forkTSChecker.ts
Labels: pr(chore)

#4457 fix: antd 4.1.2+ locale
  package.json
  packages/umi-plugin-locale/src/index.js
  packages/umi-plugin-locale/template/wrapper.jsx.tpl
  packages/umi-plugin-locale/test/index.test.js
  packages/umi-ui/client/package.json
  packages/umi/yarn.lock
  yarn.lock
Labels: 2.x, pr(bug)

#4548 fix: remove unnecessary false
  packages/types/index.d.ts
Labels: type(bug)

#4558 fix: typings.d.ts should be added in include section
  packages/create-umi-app/templates/AppGenerator/tsconfig.json
Labels: pr(chore)
